### PR TITLE
Experience and project page

### PR DESCRIPTION
**Pull request by mharshita**
@smaranjitghose  @anushbhatia  I have added hover effects and  animations to experience page cards, made the dark mode consistent with other pages and fixed the project page bug. Please review.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia I have added hover effects and animations to experience page cards, made the dark mode consistent with other pages and fixed the project page bug. Please review.

Can you please replace the data in the experience page with some other data(especially the internship one)

**Comment by smaranjitghose** [comment]
mentorship
In the mobile view, two width wise squeezed and height wise stretched mentorship cards in a single row appear visually unappealing. Can you please make it one in each row for the mobile view

**Comment by smaranjitghose** [comment]
One more bug fix that would finalize the project page:
width_difference

There appears to be a slight difference in the height of the sections

**Comment by mharshita** [comment]
@smaranjitghose  Okay sir!

**Comment by mharshita** [comment]
@smaranjitghose  Please review again.

**Pull request merged**
