### PR TITLE
Made changes in Formal education section

### PR DESCRIPTION
**Pull request by Rishikakanojia**
#83 @smaranjitghose 
screencapture-file-D-awesome-portfolio-websites-awesome-portfolio-websites-education-html-2020-08-24-14_38_48

### CODE REVIEW

**Comment by smaranjitghose** [comment]
- Reduce the spacing between MOOCS cards and try to have 5-6 in a single row ( Usually, people have 10-15 MOOCs done in and year. So that will take up unnecessary space)

**Comment by Rishikakanojia** [comment]
@smaranjitghose okay,I'll do it .

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Cards in the MOOCs sections are stretched

**Review by anushbhatia — COMMENTED** [review]
Use different Coursera image that will solve it

**Comment by smaranjitghose** [comment]
@Rishikakanojia Any updates?

**Comment by Rishikakanojia** [comment]
@smaranjitghose as suggested i made changes in moocs  section and created PR on 26/08/2020.
you can check this here - [https://github.com/smaranjitghose/awesome-portfolio-websites/pull/114](url).

**Pull request closed without merging**
