### PR TITLE
Adding about block for home page.

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
# Related Issue or bug
  - Adding About block for home page.
  - Working for both Light and Dark Theme

Fixes: #289 
 
# Screenshots

## light Theme

light

## Dark Theme

dark

@smaranjitghose @anushbhatia Review it 🔥

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Icons are pretty decent but add colours to them either by adding a circular bg to the icon or by making cards for all of them and having distinct colour added to them

**Comment by anushbhatia** [comment]
Design is pretty clean thou so do follow the same only change the presentation format for it

**Comment by anushbhatia** [comment]
https://codepen.io/jorgesanes10/pen/QdMEXr

**Comment by Vishal-raj-1** [comment]
> Icons are pretty decent but add colours to them either by adding a circular bg to the icon or by making cards for all of them and having distinct colour added to them

Sure !!

**Comment by Vishal-raj-1** [comment]
> Design is pretty clean thou so do follow the same only change the presentation format for it

Check Now !!

**Comment by Vishal-raj-1** [comment]
I have change the color of icon to white & the shadow color in dark theme.

**Comment by Vishal-raj-1** [comment]
Thank you very much @anushbhatia Sir for merging.

**Pull request merged**
