### PR TITLE
UI Improvement: fixed colors and shadow spread in Research page

### PR DESCRIPTION
**Pull request by dipanshparmar**
# Proposed Changes
 - Changed background-color
 - Reduced the spread of white shadow
   
# Screenshots
**Before**
image

**After**
image

### CODE REVIEW

**Comment by dipanshparmar** [comment]
#410

**Comment by anushbhatia** [comment]
[Use this colour a lighter shade of it](https://images.app.goo.gl/YNCbKo8BjWcQU5Fr8)
[Or like this](https://images.app.goo.gl/gbvBDjpiGuD4fXVs5)

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://dribbble.com/stories/2020/03/05/neumorphism-ui-tips
refer this for design preview

**Review by anushbhatia — COMMENTED** [review]
border-radius: 50px;
background: #ecf0f3;
box-shadow: inset 9px 9px 18px #d7dadd,
            inset -9px -9px 18px #ffffff;

**Comment by dipanshparmar** [comment]
I added #ecf0f3 as the background. If it doesn't look good then can you please let me know the exact color code you would like to see?

**Comment by anushbhatia** [comment]
user a lighter shade then https://jwoc2k20.tech/

**Comment by smaranjitghose** [comment]
After 20 mins of sitting together, @anushbhatia and I have done the entire page for you and @bhoomika07. Please follow this for all the other pages. 😅

**Pull request merged**
