### PR TITLE
Added aboutme&skills section with animation

### PR DESCRIPTION
**Pull request by gupta31**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
alignment
Please take care of alignment

**Comment by gupta31** [comment]
Sure I will correct them.

**Comment by gupta31** [comment]
- Is it fine now?

updated

**Comment by anushbhatia** [comment]
Alignment issue still persists in this pr fix this.

**Comment by gupta31** [comment]
Actually I shared one screenshot please check the alignments..I will new create PR.

**Pull request closed without merging**
