### PR TITLE
added neuromorphic effect in Research page

### PR DESCRIPTION
**Pull request by dipanshparmar**
Fixes: #392 

# Proposed Changes
 - Changed overall page color for the neuromorphic effect to take place.
 - Added neuromorphic effects to the cards
  
# Screenshots

**Before**
image

**After**
image

**On button hover**
image

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Thumbs up from my side!
@anushbhatia I believe you might have some minor changes in terms of shadow, etc to suggest

**Comment by anushbhatia** [comment]
Reduce the spread of the box shadow for white colour so that it doesn't look weird. Use background realted to white for this.pink looks pretty weird but great work 💥 never seen anyone having knowledge of neumorphic design in open source. Make these changes in next PR

**Review by anushbhatia — APPROVED** [review]

**Comment by dipanshparmar** [comment]
> Reduce the spread of the box shadow for white colour so that it doesn't look weird. Use background realted to white for this.pink looks pretty weird but great work  never seen anyone having knowledge of neumorphic design in open source. Make these changes in next PR

Sure! will make a new PR for this :smile:

**Comment by smaranjitghose** [comment]
> > Reduce the spread of the box shadow for white colour so that it doesn't look weird. Use background realted to white for this.pink looks pretty weird but great work  never seen anyone having knowledge of neumorphic design in open source. Make these changes in next PR
> 
> Sure! will make a new PR for this 😄

Looking forward to it

**Comment by dipanshparmar** [comment]
> > > Reduce the spread of the box shadow for white colour so that it doesn't look weird. Use background realted to white for this.pink looks pretty weird but great work  never seen anyone having knowledge of neumorphic design in open source. Make these changes in next PR
> > 
> > 
> > Sure! will make a new PR for this smile
> 
> Looking forward to it

making soon..

**Pull request merged**
