### PR TITLE
Fixed the position of buttons on research page.

### PR DESCRIPTION
**Pull request by luckykumarirai**
# Related Issues or bug
  Previously we observe that position of cite an abstract button is not with proper alignment in mobile view.

Fixes: #365
# Proposed Changes
 Now the position of buttons is fixed in mobile view.

# Screenshots

# Original          
x
 
# Updated
Screenshot of John Doe _ Research

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
change the overflow problem here

**Comment by luckykumarirai** [comment]
Now the overflow problem solved.

**Comment by smaranjitghose** [comment]
You are a part of NWOC right?

**Comment by luckykumarirai** [comment]
Yes, I am part of NWOC.

**Comment by luckykumarirai** [comment]
Hello sir , I am  part of nwoc as well as DWOC.please  add labels of nwoc and intermediate in this PR
.

**Pull request merged**
