### PR TITLE
All code related to Medium icon is removed.

### LINKED ISSUE #1025: Remove Medium Icon
Remove all code related to the Medium icon from the website (including main.js, style.css or index.html)

med

### PR DESCRIPTION
**Pull request by raazanand**
fixes #1025

### CODE REVIEW

**Review by smaranjitghose — COMMENTED** [review]
--col-icon-medium: #00ab6c;

^^ Remove this variable as well

**Comment by smaranjitghose** [comment]
@raazanand we are glad to see your enthusiasm for contributing to the repo. However, please make sure that you comment on the issue about your interest to complete it before giving a PR so that other contributors are aware that you are working on it

**Comment by smaranjitghose** [comment]
Additionally for all the PRs, do the following in the description:

- Mention the issue no (I have done it for you in this one)
- Put up screenshots/clips of the change 
- Synopsis of the work done ( Unordered list of short phrases) - **WHEN APPLICABLE**

Read the Contributing.MD once 😊. For this PR, just do the above change, the rest is okay!

**Comment by raazanand** [comment]
Fixes #1025

# Work Done
* removed Medium Icon code from
  * home.css
  * index.html
  * style.css

# Relevant Screenshots
## Before
Before
## After
After

**Comment by raazanand** [comment]
> --col-icon-medium: #00ab6c;
> 
> ^^ Remove this variable as well

Successfully removed the mentioned variable

**Comment by raazanand** [comment]
> @raazanand we are glad to see your enthusiasm for contributing to the repo. However, please make sure that you comment on the issue about your interest to complete it before giving a PR so that other contributors are aware that you are working on it

Thank you for guiding me, I will take care of this in future.

**Comment by smaranjitghose** [comment]
Great work @raazanand. Congratulations on getting your PR merged!

**Comment by raazanand** [comment]
> Great work @raazanand. Congratulations on getting your PR merged!
> 
> 

> Thanks 🙏  @smaranjitghose for merging my pull request .

**Pull request merged**
