### PR TITLE
New PR 

### LINKED ISSUE #1165: Bug in Experience Cards
In this section the cards look transparent which makes it look weird
image

Fix would be increase the opacity or try different combination to make it look decent

### PR DESCRIPTION
**Pull request by Devmindtk**
change background color of card blog-slider_img
Screenshot (484)
fixes #1165 @smaranjitghose

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Nice work @Devmindtk  🤛🏼

**Comment by smaranjitghose** [comment]
If you wish  you can do the same for the cards on the education page timeline as well and raise another PR.

**Comment by Devmindtk** [comment]
> Nice work @Devmindtk 🤛🏼

Thank you @smaranjitghose

**Comment by Devmindtk** [comment]
> If you wish you can do the same for the cards on the education page timeline as well and raise another PR.

yeah sure @smaranjitghose

**Comment by Devmindtk** [comment]
@smaranjitghose[](https://user-images.githubusercontent.com/91221069/153349206-67ee5604-ed6a-4810-a695-f463de7fe233.png) i have changed the background color of card as same as experience card please check is it fine?
Screenshot (485)

**Pull request merged**
