### PR TITLE
Enhanced the animations effects

### PR DESCRIPTION
**Pull request by aum-singhal**
This Pull Request is under the issue:  Add better animation effects on the pages #397

Changes I have made,

1). The animation of social icons was a bit fast so just slowed it down. Even added the transparent blur effect on background.
2).  Added few hover styling in the pages.

I am still working on it so will be updating you with more effects soon.

### CODE REVIEW

**Comment by aum-singhal** [comment]
Sir i don't know why it is showing this error. should i make a pr again??

**Comment by anushbhatia** [comment]
This is unneccesary

**Comment by aum-singhal** [comment]
Ohk Sir. Then I will try to come up with some new CSS animations soon

**Comment by anushbhatia** [comment]
Sure

**Comment by aum-singhal** [comment]
Well just wanted to confirm that I have an up to date repository and in that I am not able to see the option to switch the themes. So have you removed it permanently or its just a temporary edit?

**Pull request closed without merging**
