### PR TITLE
Updated Contribution Guidelines

### LINKED ISSUE #756: Update Contribution Guidelines
# Requirements:

- Exclusively work with [CONTRIBUTING.md](https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/CONTRIBUTING.md)
- All the images/clips used should be inside ``./readme_assets/contributing/``
- Divide the Guide into two sections

```
# A. Setting up the Project

1. Fork
2. Clone
3. Move inside the folder
4. Check Remotes
5. Add Remote to Upstream to pull changes from the original repo
6. Open VS Code
7. Run Live Server [Install it from Extensions Marketplace if not done already]

# B. Contributing to the Project

1. Pull the new changes
2. Make a feature branch
3. Do the changes
4.  Stage them
5.  Commit
6. Push it to the forked remote
7. Compare it with the desired branch
8. Make PR

# C. Instructions for PR
- Title should be brief and accurate
- Refer the issue
- Description is must. Should be in bullet points, short phrases
- Clips/snapshots before and after changes

# D. General Guidelines:

( Check my pinned message on slack for the content)

```

- For the steps like forking, cloning, raising a PR add gifs (i.e. Record Short clips using OBS Studio and convert them into GIF)
- Check my pinned message on slack for detailed content
- The above text inside the block is just a sample. __DO NOT DIRECTLY COPY PASTE. It should be elaborated___
- Remove the Topmost Section, Broken Gif and Illustration with a centre aligned image with a text over it "Contribution Guidelines)

### PR DESCRIPTION
**Pull request by Amrutha1101**
Resolved #756 
- Divided the guidelines into Part A( setting up the project which has guidelines for raising issue too) and Part B(Contributing to the project which includes guidelines for raising PR).
- Added gifs for forking and cloning the repo.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Fantastic work @Amrutha1101.  I must admit that you are among the handful of mentees whom I have interacted with so far that managed to contribute to the documentation-related parts exactly as required.

**Comment by Amrutha1101** [comment]
Thanks a lot! I know I'm spamming 😂😂

**Comment by Amrutha1101** [comment]
Thanks a lot @smaranjitghose! 
I know am spamming 😂

**Comment by smaranjitghose** [comment]
> Thanks a lot @smaranjitghose!
> I know am spamming 😂

At times, it's fine ☺😇

**Pull request merged**
