### PR TITLE
A minor typo error in README.md

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
Although, It is PR for minor typo error, but it will increase your documentation.

Thanks & Regards
Vishal

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
Thank you very much @smaranjitghose sir, It really motivates and excites me to do more in open sourcing.

**Comment by smaranjitghose** [comment]
> Thank you very much @smaranjitghose sir, It really motivates and excites me to do more in open sourcing.

Welcome to the journey 😊

**Comment by Vishal-raj-1** [comment]
@smaranjitghose It would be great if label it with beginner.

**Comment by smaranjitghose** [comment]
> @smaranjitghose It would be great if label it with beginner.

Oops 😅. I missed that.

**Pull request merged**
