### PR TITLE
Fixed education-page carousel bug

### PR DESCRIPTION
**Pull request by Pranav016**
# Related Issue or bug-

Fixes: #319 
Fixed the issue of unresponsive carousel.

# Before-
Screenshot 2020-12-16 184559

# After-
Screenshot 2020-12-16 184105

### CODE REVIEW

**Review by anushbhatia — COMMENTED** [review]
Also, add navigation buttons in next pr

**Comment by Pranav016** [comment]
> Also, add navigation buttons in next pr

Sure, I'll work on that!

**Comment by Pranav016** [comment]
Points for this PR was not added on the NWoC Leaderboard. Can you please look into it @smaranjitghose ,thanks 😃

**Comment by smaranjitghose** [comment]
> Points for this PR, merged 3 days ago were not added to the NWoC Leaderboard. Can you please look into it @smaranjitghose ,thanks 😃

Can you recheck once now?

**Comment by Pranav016** [comment]
> > Points for this PR, merged 3 days ago were not added to the NWoC Leaderboard. Can you please look into it @smaranjitghose ,thanks 😃
> 
> Can you recheck once now?

Yes, updated now. Ty

**Pull request merged**
