### PR TITLE
made changes in research page

### PR DESCRIPTION
**Pull request by mharshita**
@anushbhatia  @smaranjitghose  I have added cite button, added json file, bibtex file and created dark mode and changed the illustration for  research page ( issue : #82 ). Along with this i have also set the default theme of other html pages as "light" because of footer and nav background colors. Please review.

### CODE REVIEW

**Comment by mharshita** [comment]
image
image
image
image
image

**Review by anushbhatia — CHANGES_REQUESTED** [review]
John Doe _ Research and 6 more pages - Personal - Microsoft​ Edge 06-09-2020 10_36_23

**Comment by mharshita** [comment]
@anushbhatia  @smaranjitghose  This is probably because of PR #121. It has added toggle in the research page and i too did the same.

**Comment by mharshita** [comment]
@anushbhatia  @smaranjitghose  These changes have been made in the master branch for research page by PR #121 
image
image
image

**Comment by mharshita** [comment]
@anushbhatia I have made the changes. Please review again.

**Comment by smaranjitghose** [comment]
research
research_2

**Comment by smaranjitghose** [comment]
Can you please have a look at this?

**Comment by smaranjitghose** [comment]
research_3

**Comment by mharshita** [comment]
@anushbhatia  @smaranjitghose  PR #121  is adding toggle for dark mode and i am also doing the same.
Earlier everything was alright when i made the PR.

**Comment by smaranjitghose** [comment]
Remove the ```cited by``` column from table

**Comment by Adyasha8105** [comment]
> @anushbhatia @smaranjitghose PR #121 is adding toggle for dark mode and i am also doing the same.
> Earlier everything was alright when i made the PR.

@mharshita Just work only on that issue as I am doing that dark mode part. What say?

**Comment by mharshita** [comment]
@Adyasha8105  I think you got that wrong. I was assigned dark mode for research page and i have made it. Please refer to issue #82 . I was assigned to make dark mode for research page.

**Comment by Adyasha8105** [comment]
> @Adyasha8105 I think you got that wrong. I was assigned dark mode for research page and i have made it. Please refer to issue #82 . I was assigned to make dark mode for research page.

Oh sorry, I just put the switch button only (which is already done by someone). As it is not showing on every page, I just solved the bug.
So, if you want to change the UI of that button then u can do it and removed the previous one.

**Comment by mharshita** [comment]
@smaranjitghose  @anushbhatia  Please review again.

**Comment by smaranjitghose** [comment]
I really love what you have done with the research page @mharshita !

<p align = "center"></p>

# Some feedback for upcoming PRs:
research_page_updatte
- I would like to see if you can revamp the UI so that the papers are not represented in a boring way like Google Scholar does for us but as fancy looking list
- The headers of the title and year are not required.
- Put the button of cite to the right or someone else
** Try to work with @anushbhatia for a custom design
- The separate addition of bib file is not required. That is when someone clicks on our cite button, in the last row the bibtex should be present. That can be directly fetched from a JSON file. Other than that, we as CS undergrads and grads use Vancouver still majorly so keeping one is enough, so on clicking on the cite button, a window showing the Vancouver style ref and bib file information should pop up ( Short and sweet)
- Replace the lorem ipsum with a text like " My area of interests are: AI,Blockchain,etc" (Basically we wanna give a small overview of the domains we work in) and hence accordingly adjust the text size and graphics

**Comment by mharshita** [comment]
@smaranjitghose  Thanks sir :)
Okay!

**Pull request merged**
