### PR TITLE
added neumorphic UI in the Experience Page

### LINKED ISSUE #445: Convert Experience page UI to neumorphic UI
image

**May I work on this?**

### PR DESCRIPTION
**Pull request by dipanshparmar**
fixes #445 

Copied background color from the research page so that everything remains consistent

**Before (Light mode)**
image

**After (Light mode)**
image

**Before (Dark mode)**
image

**After (Dark mode)**
image

### CODE REVIEW

**Review by anushbhatia — APPROVED** [review]

**Comment by anushbhatia** [comment]
Great Work @dipanshparmar 🤯

**Comment by dipanshparmar** [comment]
> Great Work @dipanshparmar

Thanks @anushbhatia :smile:

**Comment by smaranjitghose** [comment]
> > Great Work @dipanshparmar
> 
> Thanks @anushbhatia 😄

The cards are well designed as per SoftUI. One small change: Remove the neumorphism from the headings like "Work Expereince" and "mentorship"

**Comment by dipanshparmar** [comment]
@smaranjitghose please have a look now.

**Comment by smaranjitghose** [comment]
expereince_nuemorphic1
Some minor tweaking in the box-shadow is required to make it in parallel with the research page cards.

There is an overflow of text in some of the cards

**Comment by dipanshparmar** [comment]
@smaranjitghose I'll make a new PR for the text-overflow bug.

**Comment by anushbhatia** [comment]
okayy

**Pull request merged**
