### PR TITLE
move the buttons towards right

### PR DESCRIPTION
**Pull request by BALARAMGHOSH**
move the buttons towards right

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@BALARAMGHOSH Hey Please resolve issues in  `assets/js/research.js`

**Comment by BALARAMGHOSH** [comment]
> @BALARAMGHOSH Hey Please resolve issues in `assets/js/research.js`

ok 👍🏻

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Add a bit of Space on left they are too squeezed on right

**Comment by smaranjitghose** [comment]
@BALARAMGHOSH Please incorporate the recent updates to fix the merge conflicts

**Comment by BALARAMGHOSH** [comment]
I do a pull request for not merge conflicts by making a new branch. Please, check it.

**Comment by smaranjitghose** [comment]
> I do a pull request for not merge conflicts by making a new branch. Please, check it.

I didn't get you. Please elaborate

**Comment by BALARAMGHOSH** [comment]
> > I do a pull request for not merge conflicts by making a new branch. Please, check it.
> 
> I didn't get you. Please elaborate

After changing in files I send the pull request from master branch. So, now I made a new branch named **button-change** and then I send the pull request.

**Comment by BALARAMGHOSH** [comment]
> > I do a pull request for not merge conflicts by making a new branch. Please, check it.
> 
> I didn't get you. Please elaborate

BALARAMGHOSH:button-change

**Comment by smaranjitghose** [comment]
Merge conflicts not fixed

**Pull request closed without merging**
