### PR TITLE
Experience screen UI fixes #411

### LINKED ISSUE #411: Experience screen UI fixes
- Work experience card's hover effect transitions are not looking good.
https://user-images.githubusercontent.com/55389276/103483710-32e0c780-4e0f-11eb-8ad5-d284897b447c.mov
- Mentorship cards' length is not consistent.
Screenshot 2021-01-03 at 10 02 49 PM

I can resolve this.
Can this issue be assigned to me.

### PR DESCRIPTION
**Pull request by Kashishjain04**
Resolve Issue #411 
Following problems are solved:
- Work experience card's hover effect transitions are not looking good.
- Mentorship cards' length is not consistent.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
card_ex
The card is barely visible

**Comment by Kashishjain04** [comment]
Screenshot 2021-01-07 at 9 54 57 PM

**Comment by anushbhatia** [comment]
image
Add a bit of padding so that card does not get merged with the footer.

**Comment by Kashishjain04** [comment]
Check now
Screenshot 2021-01-08 at 6 05 43 PM

**Comment by smaranjitghose** [comment]
> Check now
> Screenshot 2021-01-08 at 6 05 43 PM

Can you add 6 cards: two to three in each row and show us the output (push the changes)

^^ Just update the expereince.js

**Comment by Kashishjain04** [comment]
Check it out
https://user-images.githubusercontent.com/55389276/104102839-e12fb580-52c4-11eb-96df-3ac3a6f8b913.mov

**Comment by smaranjitghose** [comment]
errrro

**Comment by Kashishjain04** [comment]
That's due to hover

**Review by anushbhatia — APPROVED** [review]

**Comment by smaranjitghose** [comment]
@Kashishjain04 Can you please incorporate the latest changes to fix the merge conflicts

**Comment by smaranjitghose** [comment]
Fix the merge conflicts and please give a  new PR

**Comment by Kashishjain04** [comment]
Are merge conflicts resolved??

**Comment by smaranjitghose** [comment]
> Are merge conflicts resolved??

Give @anushbhatia and me a couple of more days. We are changing the codebase a bit. After that try once again

**Comment by Kashishjain04** [comment]
ok

**Pull request closed without merging**
