### PR TITLE
latex file added

### PR DESCRIPTION
**Pull request by ALOKARYAN51**
lets add a contribution file so we can work better, together.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Can you please share the link of the project on Overleaf so that I can have a look at the output. Unlike HTML, it's a bit difficult for me to interpret LaTeX code and under😅

**Comment by ALOKARYAN51** [comment]
https://www.overleaf.com/project/5f53428a9841ac0001664d1d 
sir @smaranjitghose

**Comment by smaranjitghose** [comment]
> https://www.overleaf.com/project/5f53428a9841ac0001664d1d
> sir @smaranjitghose

You forgot to change the permission for everyone to see😅

**Comment by ALOKARYAN51** [comment]
https://www.overleaf.com/read/gksqsbjngbbd
@smaranjitghose sir please check it once

**Comment by smaranjitghose** [comment]
@ALOKARYAN51 Seeing you make this from scratch is truly amazing😍. Nice job!
latex_work
# Some Suggestions for future updates:
- In Latex always name the first file as ```main.tex```.  ( Same for the CLS one)
- Increase the size of the name ( also make it something generic like John Doe)
- Add options for social media icons of twitter, google scholar, kaggle,dribble
- Reduce the width of the Headings
- DM me in slack, I'll share a copy of my own resume so that you can have a better idea of the UI ( as well as content)
- You have commented the necessary sections but I would request you to elaborate more so that even novices can read your latex code and understand

**Pull request merged**
