### PR TITLE
Added zoom effect to the cards on hover

### LINKED ISSUE #390: Make some elements more dynamic!
**Is your feature request related to a problem? Please describe.**
Not a problem. It is something that would enhance the User experience.

**Describe the solution you'd like**
Make these elements more dynamic by adding animations or something.

### These are just plain static cards, I would like to add an image zoom effect on hover on these cards.
image

### These cards are also static, I would like them to pop up a little on hover or slide left/ right on scroll.
image

### PR DESCRIPTION
**Pull request by Pranav016**
# Related Issues or bug
Fixes #390 

# Proposed Changes
- Added zoom animation over the cards that were static. (Main feature added/ issue resolved)
- Also increased the height of the main page because it wasn't looking very visually pleasing. (minor change)

Example- 
Before-
Screenshot 2020-12-30 200528
After-
Screenshot 2020-12-30 200559
Before-
Screenshot 2020-12-30 200627
After-
Screenshot 2020-12-30 200742

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@Pranav016 Please pull the changes from the current upstream repo. Your branch is too much behind

**Comment by Pranav016** [comment]
> @Pranav016 Please pull the changes from the current upstream repo. Your branch is too much behind

Yes, I'll pull the upstream to master. My remote master is behind, but my local master was upto date so this PR was upto date👍😃

**Comment by Pranav016** [comment]
> @Pranav016 Please pull the changes from the current upstream repo. Your branch is too much behind

Also can you add points for NWoC for the PR..

**Comment by smaranjitghose** [comment]
> > @Pranav016 Please pull the changes from the current upstream repo. Your branch is too much behind
> 
> Also can you add points for NWoC for the issue and the PR..

Sure

**Comment by smaranjitghose** [comment]
> > @Pranav016 Please pull the changes from the current upstream repo. Your branch is too much behind
> 
> Yes, I'll pull the upstream to master. My remote master is behind, but my local master was upto date so this PR was upto date👍😃

Actually the PR was not upto date

**Comment by Pranav016** [comment]
> > > @Pranav016 Please pull the changes from the current upstream repo. Your branch is too much behind
> > 
> > 
> > Yes, I'll pull the upstream to master. My remote master is behind, but my local master was upto date so this PR was upto date👍😃
> 
> Actually the PR was not upto date

Hmm, let me check. I updated my master before working on it. Should I update and make a PR again then? I think if it were behind it would have given some merge conflicts..

**Comment by smaranjitghose** [comment]
> > > > @Pranav016 Please pull the changes from the current upstream repo. Your branch is too much behind
> > > 
> > > 
> > > Yes, I'll pull the upstream to master. My remote master is behind, but my local master was upto date so this PR was upto date👍😃
> > 
> > 
> > Actually the PR was not upto date
> 
> Hmm, let me check. I updated my master before working on it. Should I update and make a PR again then? I think if it were behind it would have given some merge conflicts..
> Let me know the course of action, I'd do it instantly :)

No worries, I have taken care of it.  Next PR onwards you can do it with recent changes😊

**Pull request merged**
