### PR TITLE
Created travel vlog summary template page

### LINKED ISSUE #750: Travel Vlog Summary Template Page
[Reference](https://codepen.io/suez/full/AXQaEg)

[Footer Wave Reference](https://codepen.io/goodkatz/pen/LYPGxQz)

## Instructions

- Make the cards square in shape
- Add a title like "Trip to the X" before the cards
- For the purpose of the demo, replace the "section 1", "section 2", etc texts with "Day 1", "Day 2", "Day 3", etc
- All the images should be placed inside `./assets/images/travel/trip1/`
- Take the images from unsplash. ( For example tourist spots in New Delhi)
- Name the images properly
- Do not add a tab in the Nav Bar. The page would be accessed directly with ``./travel_temp.html``
- The CSS file should be `./assets/css/travel_temp.css` and the Js should be ``./assets/js/travel_temp.js``
- To add or remove cards and the details for the same, it should be done from a JSON variable inside conf_temp.js. Check out research.js for reference.

### PR DESCRIPTION
**Pull request by forkbikash**
Fixes #750
Created the full template which:
1. Uses JSON variable to load content dynamically.
2. Also works with portrait pictures.
3. Images placed inside ./assets/images/travel/trip1/
4. CSS file placed as ./assets/css/travel_temp.css
5. Js file placed as ./assets/js/travel_temp.js

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Fantastic work @forkbikash. We need to figure out something for the mobile view. Currently, its' little crammed

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/40017559/122912187-af437480-d375-11eb-85e1-e389f0484e6b.mp4

Put this in a single div so that they can scroll together along with them. Currently, the text moves and the svg remains there.

**Comment by forkbikash** [comment]
Made the changes @anushbhatia

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
# Further Work:

- Convert the CSS to SASS
- Define the Page for Dark Mode
- Make the UI suitable for Mobile View
- Transition into React

Nice work @forkbikash . We really appreciate your efforts. Keep it up. If you wish you can raise issues for the above.

**Pull request merged**
