### PR TITLE
added hover effect to the navbar in react project

### PR DESCRIPTION
**Pull request by alceil**
I have added a hover effect to the navbar of the react project. It lacked a hover effect in the nav bar as the original website.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Add a grow animation in this just like the HTML one

**Comment by alceil** [comment]
Okay got it

**Comment by smaranjitghose** [comment]
Please pull the recent changes to fix the merge conflict

**Comment by smaranjitghose** [comment]
- Also, have a look at the suggestion I gave in the corresponding issue.
- Underline is too long
Too_Big

**Comment by alceil** [comment]
got it will fix it soon

**Comment by alceil** [comment]
I have added the required changes please check @smaranjitghose

**Comment by anushbhatia** [comment]
Great Work

**Comment by alceil** [comment]
Thanks

**Pull request merged**
