### PR TITLE
#668 Footer Design

### PR DESCRIPTION
**Pull request by dpshikha476**
Issue Fixed: #668 

Changed the footer design.

@smaranjitghose  Please review it and let me know if you need any changes.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@anushbhatia @phreakyphoenix Your opinions?

Will be merged once I approve

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Change the font to the same as the theme.
Also, try not using complete black there instead of using a darker shade of grey.
https://material.io/design/color/dark-theme.html

**Comment by dpshikha476** [comment]
> Change the font to the same as the theme.
> Also, try not using complete black there instead of using a darker shade of grey.
> https://material.io/design/color/dark-theme.html

Done sir!

**Comment by smaranjitghose** [comment]
The footer is unresponsive for the majority of mobile screens. Please take care of that

**Comment by dpshikha476** [comment]
> The footer is unresponsive for the majority of mobile screens. Please take care of that

Done!

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
A slight issue with the iphone SE screen issue. Rest looks good!

**Pull request merged**
