### PR TITLE
Updates to fix project description bug in project page.

### PR DESCRIPTION
**Pull request by MaheshBabu11**
This is a fix for the description bug on the project page.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
This doesn't limit the description to a limit of words mentioned the in issue #1140

**Comment by MaheshBabu11** [comment]
> This doesn't limit the description to a limit of words mentioned the in issue #1140

Yes, I didn't get what you were previously said about the word limit. Will fix it and update the code.

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Instead of truncate on every input can't u put that inside the foreach loop or anywhere before that restricting the characters to upto certain limit

**Comment by MaheshBabu11** [comment]
I tried that but since it's a const array, it is unable to modify that in a similar way. Do you have any advice on that?

**Comment by MaheshBabu11** [comment]
No problem. I have updated that in the latest commit. Please do review that.

**Comment by smaranjitghose** [comment]
## Feedback:

project_page

^^ Refer the above snap
- On hover, the shadow should cover the entire card
- The text should be positioned on the centre
- The subheading/description should be placed below it (centre aligned)
- The preview and github icons should be right aligned

**Pull request closed without merging**
