### PR TITLE
Contact Page

### PR DESCRIPTION
**Pull request by akshita2903**
Sir,Please have a look into the responsive contact page,I created.
I have removed that image and that " I am XYZ "part and have also added dark theme and Light theme to contact page.
as prescribed by you.
Suggest any improvement if needed.
ThankYou..
Screenshot (6)

### CODE REVIEW

**Comment by smaranjitghose** [comment]
contact_issue
This is the deploy of your PR. Please have a look and try fix it.
Please include the contact in the navbar for making it easier to navigate to it

**Comment by akshita2903** [comment]
Sir I have made changes to my file and also added contact to navbar.Please look into it and tell whether this is OK or not

**Comment by akshita2903** [comment]
Sir I have made fixed the issue as prescribed by you and have also added contact to navigation bar.
Please look into it and give your review accordingly.
ThankYou..

**Comment by anushbhatia** [comment]
John Doe _ Home and 3 more pages - Personal - Microsoft​ Edge 16-09-2020 13_24_20

**Comment by akshita2903** [comment]
Got it Sir. Will improve it

**Comment by akshita2903** [comment]
Screenshot (7)
@anushbhatia  Sir I  have rectified the error of navbar .Please look into it.

**Comment by akshita2903** [comment]
@smaranjitghose and @anushbhatia  Sir I want to ask why it is showing "this branch has conflicts that must be resolved with assets/js/main.js file".Please explain it

**Comment by smaranjitghose** [comment]
> @smaranjitghose and @anushbhatia Sir I want to ask why it is showing "this branch has conflicts that must be resolved with assets/js/main.js file".Please explain it

There are certain changes done to those files while you were working on a separate branch for these changes. So you need to do a git pull upstream to inculcate them in your copy of the project

**Comment by akshita2903** [comment]
> changes

I did but again its showing the same.Please help me out.

**Comment by akshita2903** [comment]
> > @smaranjitghose and @anushbhatia Sir I want to ask why it is showing "this branch has conflicts that must be resolved with assets/js/main.js file".Please explain it
> 
> There are certain changes done to those files while you were working on a separate branch for these changes. So you need to do a git pull upstream to inculcate them in your copy of the project

I did but again its showing the same error.Please help me out

**Pull request closed without merging**
