### PR TITLE
Added text animations

### PR DESCRIPTION
**Pull request by m-code12**
Fixes: #523

### CODE REVIEW

**Comment by m-code12** [comment]
@smaranjitghose @anushbhatia Please can you merge this pr, I had created two pr's before for this issue but those couldn't get merged because of conflicts.

**Comment by anushbhatia** [comment]
The only thing I can see preloader.

**Comment by m-code12** [comment]
> The only thing I can see preloader.

That's only in the home page, I had pulled all the changes even then it isn't working properly. The rest of the pages are working perfectly @anushbhatia @smaranjitghose

**Comment by m-code12** [comment]
I raised this new pr but even then I am facing that issue

**Comment by anushbhatia** [comment]
fork the repo again and then push your changes there and give a pr

**Pull request closed without merging**
