### PR TITLE
Project Card Bug #511

### PR DESCRIPTION
**Pull request by Chaitanya31612**
Fixed Project Card Bug.
image

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> Fixed Project Card Bug.
> image

Check for mobile view. Highly unresponsive

**Comment by smaranjitghose** [comment]
unresponcivve

** On Focus

**Comment by smaranjitghose** [comment]
vfgb

Without focus/hover

**Comment by Chaitanya31612** [comment]
@smaranjitghose okay, I will fix these issues.

**Comment by smaranjitghose** [comment]
> @smaranjitghose okay, I will fix these issues.

Any updates?

**Comment by Chaitanya31612** [comment]
> > @smaranjitghose okay, I will fix these issues.
> 
> Any updates?

It's already done. I've made pr on the same day for responsiveness.

**Comment by smaranjitghose** [comment]
project_casr
The bug in the mobile view still persists

**Pull request closed without merging**
