### PR TITLE
Improve Footer Design Fixes #265

### LINKED ISSUE #265: Improve Footer Design

### LINKED ISSUE #324: Direct change in style.css affect About section of Homepage.
# Describe the bug

Now because of last [commit](https://github.com/smaranjitghose/awesome-portfolio-websites/commit/4d0095b62bd2dfdceb4eeddc6f0316122796276d)  by @Pranav016 home page is look like

## Home 

home bug

## About 

about bug

# To Reproduce 
1. Since I have given style to .card directly. I will use some class for that cards
2. @Pranav016 collaborate with me (we can talk, will use stack for that purpose) 

# Expected behavior

## Home
home

## About
about sghj

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
# Related Issue or bug
  - Improve footer design

Fixes #265 & resolve #324 

# Proposed Changes
 - Adding mx-auto to footer form for tab view.
-  Change display `block` to `flex`. And place contact@gmail section in another block.

# Additional Info
  - Add links of open source program in README. Now on clicking the images we can go their respective websites.
  
# Screenshots

## Desktop View : 

desk

## Mobile View :

mobi

@smaranjitghose @anushbhatia review these changes 🔥

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> # Related Issue or bug
> * Improve footer design
> 
> Fixes: #265
> 
> # Proposed Changes
> * Adding mx-auto to footer form for tab view.
> * Change display `block` to `flex`. And place contact@gmail section in another block.
> 
> # Additional Info
> * Add links of open source program in README. Now on clicking the images we can go their respective websites.
> 
> # Screenshots
> ## Desktop View :
> desk
> 
> ## Mobile View :
> mobi
> 
> @smaranjitghose @anushbhatia review these changes 🔥

Since we have a fixed navbar, I think with respect to design ( for mobile view), we should replace the element containing the "John Doe" image from the footer

**Comment by Vishal-raj-1** [comment]
> Since we have a fixed navbar, I think with respect to design ( for mobile view), we should replace the element containing the "John Doe" image from the footer

Replace with `?`. Should I remove logo for mobile Or anything specific you need ? @smaranjitghose @anushbhatia

**Comment by Vishal-raj-1** [comment]
@anushbhatia I think it will be nice if I do `display; none;` for mobile view. It looks awesome to me.

footer

**Comment by smaranjitghose** [comment]
> > Since we have a fixed navbar, I think with respect to design ( for mobile view), we should replace the element containing the "John Doe" image from the footer
> 
> Replace with `?`. Should I remove logo for mobile Or anything specific you need ? @smaranjitghose @anushbhatia

Pardon me😅. I meant remove

**Comment by smaranjitghose** [comment]
> @anushbhatia I think it will be nice if I do `display; none;` for mobile view. It looks awesome to me.
> 
> footer
> 
> P.S : Waiting for your reply.

Definitely!

**Comment by Vishal-raj-1** [comment]
@smaranjitghose @anushbhatia Sir 😀 This is done 🔥 You can check now.

**Comment by Vishal-raj-1** [comment]
I have solved the bug and fixes #324

**Comment by anushbhatia** [comment]
image
look through these changes too

**Comment by Vishal-raj-1** [comment]
> look through these changes too

What actually happen here is ? We are adding more icons to footer and homepage. So, It will look nice. After those PR's got merged.

**Comment by anushbhatia** [comment]
Sure after that make the required alignmentt

**Comment by Vishal-raj-1** [comment]
Thanks for merging @anushbhatia Sir 🔥 

> Sure after that make the required alignmentt

Sure !!

**Pull request merged**
