### PR TITLE
Added Education timeline & added poppins fonts for all pages.

### PR DESCRIPTION
**Pull request by shubhkhanna**
@smaranjitghose sir, @sakshi1499 please review it.
#14

### CODE REVIEW

**Comment by sakshi1499** [comment]
Also, the formal education header looks strange. Can you please align it in the center/ remove or suggest something else we could do with it. @shubhkhanna

**Comment by shubhkhanna** [comment]
Screenshot (19)
@sakshi1499 see this

**Comment by smaranjitghose** [comment]
edu_error
This is the preview we are getting from https://deploy-preview-38--awesome-portfolio-website.netlify.app/education.html

**Comment by smaranjitghose** [comment]
@sakshi1499 Can you suggest @shubhkhanna A timeline design where the leaves are the cards and the main trunk is the centre of the timeline

**Comment by shubhkhanna** [comment]
Screenshot (20)
@smaranjitghose sir, I'm getting this.

**Comment by arghac14** [comment]
@shubhkhanna  the problem is that the horizontal connecting lines of the timeline is not responsive/not sticking to the vertical line (you can check this by resizing the window).

**Comment by arghac14** [comment]
@shubhkhanna Also, put the MIT.png image in the images directory ( assets/images/education-page/MIT.png).

**Pull request closed without merging**
