### PR TITLE
Added events page

### LINKED ISSUE #572: Event/Talk Throwback page

### PR DESCRIPTION
**Pull request by parthpandyappp**
Created a simple & sober design for the Events page resembling one which we'd already. This fixes #572

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
logos are getting stretched in laptop and mobile preview.
also centre align the logos in mobile view

**Comment by parthpandyappp** [comment]
@anushbhatia Okay, I'll fix it soon!

**Comment by parthpandyappp** [comment]
Hey! @anushbhatia I've fixed that strethcy issue! Have a look!

**Comment by smaranjitghose** [comment]
Please have a look at the requirement of the page. This is not at all relatable

**Pull request closed without merging**
