### PR TITLE
fixes #989 : Removed ScrollBar track during Preloader animation

### LINKED ISSUE #989: Remove ScrollBar Track during Preloader animation
Scroll_bar

### PR DESCRIPTION
**Pull request by aashimawadhwa**
Fixed #989
updated the visibility of overflow from scroll to visible in style.css

Screenshot_from_2021-07-25_02-37-01

### CODE REVIEW

**Comment by anushbhatia** [comment]
Great Work Which program do you belong to if you could specify

**Comment by aashimawadhwa** [comment]
I am pursuing cse , In my freshmen year right now .

**Comment by aashimawadhwa** [comment]
I am working under LGMSoC program @anushbhatia

**Comment by aashimawadhwa** [comment]
Please tell me why this test case failed ?

**Comment by smaranjitghose** [comment]
> Please tell me why this test case failed ?

That's a bug with the GitHub Action

**Pull request merged**
