### PR TITLE
Experience page issue solved

### PR DESCRIPTION
**Pull request by Ayush0730**
Issue #500 solved 

screenshots : 
1)
image
On full screen size

2)
image
On screensize around 900px (medium)

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
Flipkart logo should cover the complete logo of the card try doing that

**Comment by Ayush0730** [comment]
modified the code so that the companies logo (flipkart logo) covers full card height

**Comment by Ayush0730** [comment]
image

**Review by smaranjitghose — APPROVED** [review]

**Comment by anushbhatia** [comment]
Now you can work on mentorship card change their colour and also solve the overflow issue on mobile

**Pull request merged**
