### PR TITLE
Added new UI in Projects section

### PR DESCRIPTION
**Pull request by dipanshparmar**
Fixes: #399 

# Proposed Changes
 - Updated the UI
  
# Screenshots
**Before (Light mode)**
image

**After (Light mode)**
image

***

**Before (Dark mode)**
image

**After (Dark mode)**
image

***

**Before (Label design)**
image

**After (Label design)**
image

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@smaranjitghose and @anushbhatia your opinions on this?

**Comment by smaranjitghose** [comment]
The overall card design looks better. I am looking forward to integrating this!

# Feedback:
1) Transparency bug:

transparency_issues

2) For the dark mode, on hover the background should be transparent instead of the magenta-ish color. Like it is in the current version

3) Make the cards slightly bigger (Increase the width and height)

4) Increase the no of cards in a row to 3 ( grid size). The distance between the cards and the border of the page can be reduced further as well

5) The preview and github icons can be shifted towards bottom right

6) The helper text in the search bar can be made "Search by tech. Eg: Machine Learning"

7) We can extend the search feature not only to the tags but also to the names of the project

8) The search bar can be made smaller in size and repositioned somewhere else on the page ( OPTIONAL)

9) Remove the "ToTop Button"

**Comment by dipanshparmar** [comment]
@smaranjitghose Is it ok if I apply the 3rd and the 7th feature in new PRs?

**Comment by smaranjitghose** [comment]
> @smaranjitghose Is it ok if I apply the 4th and the 7th feature in new PRs?

Sure

**Comment by smaranjitghose** [comment]
One small change required:

# Hover effect:

## Dark Mode: ✅✅

trasparency_2

## Light Mode:  (Make it the same as above)

trasparency_1

**Review by smaranjitghose — APPROVED** [review]

**Comment by dipanshparmar** [comment]
> One small change required:
> 
> # Hover effect:
> ## Dark Mode: 
> trasparency_2
> 
> ## Light Mode: (Make it the same as above)
> trasparency_1

Like same as it is in the dark mode?

**Comment by smaranjitghose** [comment]
> > One small change required:
> > # Hover effect:
> > ## Dark Mode:
> > trasparency_2
> > ## Light Mode: (Make it the same as above)
> > trasparency_1
> 
> Like same as it is in the dark mode?

Yes

**Comment by smaranjitghose** [comment]
Awaiting the follow up PR 😊

**Comment by dipanshparmar** [comment]
> Awaiting the follow up PR

Coming up soon... :smile:

**Pull request merged**
