### PR TITLE
project bug fixed

### LINKED ISSUE #598: Project Card bug
Currently, the GitHub and desktop icons are hidden in this so we need to resolve this on click they should be visible.
https://user-images.githubusercontent.com/40017559/108893462-1f93f080-7637-11eb-9dca-bb2233bb66b9.png

### PR DESCRIPTION
**Pull request by Abhijay007**
#598 

preview:

project-bug-changes

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Bug

This bug remains.

Make a new PR, remove all code related to the tags and searching via tags. And get done with it

**Comment by Abhijay007** [comment]
@smaranjitghose sir my name is abhijay 😄 you assigned points to Ashutosh 😅

**Comment by Abhijay007** [comment]
> Bug
> 
> This bug remains.
> 
> Make a new PR, remove all code related to the tags and searching via tags. And get done with it

ok sir I will do this 👍

**Comment by smaranjitghose** [comment]
@Abhijay007 
Raise another PR to finish off this [one](https://github.com/smaranjitghose/awesome-portfolio-websites/issues/598)
(Just the Card Animation, Card UI, Grid Size ).

**Comment by Abhijay007** [comment]
> @Abhijay007
> Raise another PR to finish off this [one](https://github.com/smaranjitghose/awesome-portfolio-websites/issues/598)
> (Just the Card Animation, Card UI, Grid Size ).

ok sir

**Comment by Abhijay007** [comment]
> @smaranjitghose sir my name is abhijay 😄 you assigned points to Ashutosh 😅

>@Abhijay007
Raise another PR to finish off this one
(Just the Card Animation, Card UI, Grid Size ).

sir do I need to make a new PR in order to change this?

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir my name is abhijay 😄 you assigned points to @ashuvssut 😅

I know you. I think I selected the wrong label by chance

**Comment by smaranjitghose** [comment]
> > @smaranjitghose sir my name is abhijay 😄 you assigned points to Ashutosh 😅
> 
> sir do I need to make a new PR in order to change this?

Nope, I altered it

**Comment by Abhijay007** [comment]
@

> Bug
> 

@smaranjitghose sir this bug is solved now:
bug

but sir, I don't think that opening a separate PR is required I hardly changed 4-5 lines of code.
can I push these changes in my existing  PR?

**Comment by smaranjitghose** [comment]
> @
> 
> > Bug
> 
> @smaranjitghose sir this bug is solved now:
> bug
> 
> but sir, I don't think that opening a separate PR is required I hardly changed 4-5 lines of code.
> can I push these changes in my existing PR?

Ahh. do give a new PR.

Also, I would suggest that you remove the entire feature of having tags because as the # of projects grows, it would be difficult to maintain

**Comment by Abhijay007** [comment]
Ok sir

**Comment by Abhijay007** [comment]
> Also, I would suggest that you remove the entire feature of having tags because as the # of projects grows, it would be difficult to maintain

@smaranjitghose sir if we removed the entire feature of tags then we may also need to change or remove that search part from the project page. 
so can I also remove that too?

**Comment by smaranjitghose** [comment]
Yes

The "search with tags" feature

**Comment by Abhijay007** [comment]
> Also, I would suggest that you remove the entire feature of having tags because as the # of projects grows, it would be difficult to maintain

@smaranjitghose sir done with the code changes:

changes-project-tags

I removed code for tags and search div and make it responsive for all possible screens.

do I need to change something?
can I open a PR for this?

**Comment by smaranjitghose** [comment]
> > Also, I would suggest that you remove the entire feature of having tags because as the # of projects grows, it would be difficult to maintain
> 
> @smaranjitghose sir done with the code changes:
> 
> changes-project-tags
> 
> I removed code for tags and search div and make it responsive for all possible screens.
> 
> do I need to change something?
> can I open a PR for this?

Perfect. You can change the grid size so that for the web view we can have 3 cards per row.

Also, for the mobile view (based upon your screenshot), the preview and github icons should be at the bottom right (This is one thing I believe that needs a fix)

**Comment by Abhijay007** [comment]
> Perfect. You can change the grid size so that for the web view we can have 3 cards per row.
> Also, for the mobile view (based upon your screenshot), the preview and github icons should be at the bottom right (This is one thing I believe that needs a fix)

ok sir I will do this 👍

**Comment by Abhijay007** [comment]
> Perfect. You can change the grid size so that for the web view we can have 3 cards per row.
> Also, for the mobile view (based upon your screenshot), the preview and github icons should be at the bottom right (This is one thing I believe that needs a fix)

@smaranjitghose sir, done with the code changes:

bug-changes

can I open a PR for this?

do I need to change something?

**Comment by smaranjitghose** [comment]
> > Perfect. You can change the grid size so that for the web view we can have 3 cards per row.
> > Also, for the mobile view (based upon your screenshot), the preview and github icons should be at the bottom right (This is one thing I believe that needs a fix)
> 
> @smaranjitghose sir, done with the code changes:
> 
> bug-changes
> 
> can I open a PR for this?
> 
> do I need to change something?

Sure. Do give a PR

**Pull request merged**
