### PR TITLE
Project_Card_Tag_Bug #513

### PR DESCRIPTION
**Pull request by Chaitanya31612**
image

### CODE REVIEW

**Comment by smaranjitghose** [comment]
The bug is still there

**Comment by Chaitanya31612** [comment]
> The bug is still there

Can you describe what exactly is the bug?

**Comment by smaranjitghose** [comment]
> > The bug is still there
> 
> Can you describe what exactly is the bug?

The small white comma

**Comment by Chaitanya31612** [comment]
> > > The bug is still there
> > 
> > 
> > Can you describe what exactly is the bug?
> 
> The small white comma

Oh!! I haven't seen that, is the margin and spacing fine or needs to be removed?

**Comment by smaranjitghose** [comment]
> > > > The bug is still there
> > > 
> > > 
> > > Can you describe what exactly is the bug?
> > 
> > 
> > The small white comma
> 
> Oh!! I haven't seen that, is the margin and spacing fine or needs to be removed?

Margin and spacing seems fine

**Comment by Chaitanya31612** [comment]
> > > > > The bug is still there
> > > > 
> > > > 
> > > > Can you describe what exactly is the bug?
> > > 
> > > 
> > > The small white comma
> > 
> > 
> > Oh!! I haven't seen that, is the margin and spacing fine or needs to be removed?
> 
> Margin and spacing seems fine

Cool,
Now you can review my pull request, it's solved
image

**Pull request merged**
