### PR TITLE
Added text animations

### PR DESCRIPTION
**Pull request by m-code12**
Fixes: #523 

https://user-images.githubusercontent.com/53649201/108547064-0118b700-7310-11eb-8e25-33d492eecbf1.mp4

### CODE REVIEW

**Comment by m-code12** [comment]
@smaranjitghose @anushbhatia Please review this pr.

**Comment by anushbhatia** [comment]
Make a squash commit so that this can be resolved

**Comment by m-code12** [comment]
> Make a squash commit so that this can be resolved

I have resolved the conflicts.

**Comment by smaranjitghose** [comment]
@m-code12 please check the [deploy preview](https://deploy-preview-588--awesome-portfolio-website.netlify.app/experience.html) the footer and the other pages are messing up.

Please pull the recent changes and give a new PR

**Pull request closed without merging**
