### PR TITLE
Updated the Education section to be more mobile friendly/ added cards animations and new image.

### PR DESCRIPTION
**Pull request by Pranav016**
## Pull request description-
Updated the Education section to be more mobile friendly/ added cards animations and new image.

# Fixes issue #263 

## Work Done- 
- Added new cards with animations to `education.html`
- Added new image for the cards
- Made cards responsive
- Added CSS by updating `education.css` and `style.css`
- **Optimized them for dark mode as well.**

**Checkout out the video provided below where I have shown how the section works in desktop and mobile view and also in Light and Dark Mode** 

## Video Reference for working of the page and responsiveness proofs- 
# [Watch Video](https://drive.google.com/file/d/1H3LL26mlpoW0aY1ZVFDDqASBeRadRAvI/view?usp=sharing)

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> ## Pull request description-
> Updated the Education section to be more mobile friendly/ added cards animations and new image.
> 
> # Fixes issue #263
> ## Work Done-
> * Added new cards with animations to `education.html`
> * Added new image for the cards
> * Made cards responsive
> * Added CSS by updating `education.css` and `style.css`
> * **Optimized them for dark mode as well.**
> 
> **Checkout out the video provided below where I have shown how the section works in desktop and mobile view and also in Light and Dark Mode**
> 
> ## Video Reference for working of the page and responsiveness proofs-
> # [Watch Video](https://drive.google.com/file/d/1H3LL26mlpoW0aY1ZVFDDqASBeRadRAvI/view?usp=sharing)

Nice work @Pranav016 !

## Suggested Changes

1. Could you please reduce the size of the education cards (college ones) by 75% of the current size
2. Instead of Lorem Ipsum, use the default details used in the  website
3.  Each card should have:
        - Name of Institution
        - Degree
        - Duration
        - A space for logo or picture
        - Activities there
4. Remove the Badge Section
5. Pull the changes for the addition of the carosoul

**Comment by Pranav016** [comment]
> > ## Pull request description-
> > Updated the Education section to be more mobile friendly/ added cards animations and new image.
> > # Fixes issue #263
> > ## Work Done-
> > 
> > * Added new cards with animations to `education.html`
> > * Added new image for the cards
> > * Made cards responsive
> > * Added CSS by updating `education.css` and `style.css`
> > * **Optimized them for dark mode as well.**
> > 
> > **Checkout out the video provided below where I have shown how the section works in desktop and mobile view and also in Light and Dark Mode**
> > ## Video Reference for working of the page and responsiveness proofs-
> > # [Watch Video](https://drive.google.com/file/d/1H3LL26mlpoW0aY1ZVFDDqASBeRadRAvI/view?usp=sharing)
> 
> Nice work @Pranav016 !
> 
> ## Suggested Changes
> 1. Could you please reduce the size of the education cards (college ones) by 75% of the current size
> 2. Instead of Lorem Ipsum, use the default details used in the  website
> 3. Each card should have:
>    - Name of Institution
>    - Degree
>    - Duration
>    - A space for logo or picture
>    - Activities there
> 4. Remove the Badge Section
> 5. Pull the changes for the addition of the carousel

Sure! I'll start working on the suggested changes 😄

**Comment by Pranav016** [comment]
> 1. Could you please reduce the size of the education cards (college ones) by 75% of the current size
Their size should be updated to 75% of their current size or reduced by 75%?

**Comment by smaranjitghose** [comment]
> > 1. Could you please reduce the size of the education cards (college ones) by 75% of the current size
> 
> Their size should be updated to 75% of their current size or be reduced by 75%?

Updated to 75% of current size

**Comment by anushbhatia** [comment]
https://codepen.io/RomanKl/pen/KyqaKx
https://codepen.io/clintabrown/pen/yoFcC
Or you add a fade slider which moves along references https://codepen.io/ReGGae/pen/povjKxV showing all the education with year

**Comment by smaranjitghose** [comment]
> https://codepen.io/RomanKl/pen/KyqaKx
> https://codepen.io/clintabrown/pen/yoFcC
> Or you add a fade slider which moves along references https://codepen.io/ReGGae/pen/povjKxV showing all the education with year

@Pranav016 Any updates?

**Comment by Pranav016** [comment]
> > https://codepen.io/RomanKl/pen/KyqaKx
> > https://codepen.io/clintabrown/pen/yoFcC
> > Or you add a fade slider which moves along references https://codepen.io/ReGGae/pen/povjKxV showing all the education with year
> 
> @Pranav016 Any updates?

Yes, will make a PR today. Actually had an exam so couldn't work on it much. Exams are now over!

**Comment by smaranjitghose** [comment]
> > > https://codepen.io/RomanKl/pen/KyqaKx
> > > https://codepen.io/clintabrown/pen/yoFcC
> > > Or you add a fade slider which moves along references https://codepen.io/ReGGae/pen/povjKxV showing all the education with year
> > 
> > 
> > @Pranav016 Any updates?
> 
> Yes, will make a PR today. Actually had an exam so couldn't work on it much. Exams are over now!

No worries. Take your time

**Comment by Pranav016** [comment]
> > ## Pull request description-
> > Updated the Education section to be more mobile friendly/ added cards animations and new image.
> > # Fixes issue #263
> > ## Work Done-
> > 
> > * Added new cards with animations to `education.html`
> > * Added new image for the cards
> > * Made cards responsive
> > * Added CSS by updating `education.css` and `style.css`
> > * **Optimized them for dark mode as well.**
> > 
> > **Checkout out the video provided below where I have shown how the section works in desktop and mobile view and also in Light and Dark Mode**
> > ## Video Reference for working of the page and responsiveness proofs-
> > # [Watch Video](https://drive.google.com/file/d/1H3LL26mlpoW0aY1ZVFDDqASBeRadRAvI/view?usp=sharing)
> 
> Nice work @Pranav016 !
> 
> ## Suggested Changes
> 1. Could you please reduce the size of the education cards (college ones) by 75% of the current size
> 2. Instead of Lorem Ipsum, use the default details used in the  website
> 3. Each card should have:
>    - Name of Institution
>    - Degree
>    - Duration
>    - A space for logo or picture
>    - Activities there
> 4. Remove the Badge Section
> 5. Pull the changes for the addition of the carosoul

All these changes are done 👍

**Comment by Pranav016** [comment]
My code was completely responsive (as you have seen in the video above)but I noticed the new carousel I pulled wasn't very responsive. I would like to raise another issue to fix that. Should I go for it?

**Comment by smaranjitghose** [comment]
> My code was completely responsive (as you have seen in the video above) but I noticed the new carousel I pulled wasn't very responsive. I would like to raise another issue to fix that. Should I go for it?

Sure.
Also, I would suggest removing the certificate button for the education cards since most people visiting one's website won't be interested in seeing how one's college degree looks

**Pull request merged**
