### PR TITLE
headings and subheadings update 

### PR DESCRIPTION
**Pull request by jatinjain001**
Kindly check it and please let me know if there need to change in headings or color.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
1. Avoid Capitilization
2. #4c8bf5 try using this colour code avoid inline css please it becomes too difficult to debug

**Comment by jatinjain001** [comment]
Okay

**Comment by jatinjain001** [comment]
changes done, If anything needs to change feel free to say , if this pr is merged then please take it under dwoc also.

**Comment by smaranjitghose** [comment]
This is not according to what was required.
Reverted

**Comment by jatinjain001** [comment]
you described the issue that you need even number of words in headings, with your given color code . then what you need please explain it.

**Comment by smaranjitghose** [comment]
> 
> 
> you described the issue that you need even number of words in headings, with your given color code . then what you need please explain it.

Even number of words, with one half in color a and the second half in color b where a,b is from our color palette

**Comment by jatinjain001** [comment]
Okk just change of color is needed, I will do it ☺

**Pull request merged**
