### PR TITLE
new icons added and improvement in footer interface

### PR DESCRIPTION
**Pull request by sauravvsonu**
solved issue #316 

//before
image
image

//after

image

image

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@sauravvsonu Brother You have open same PR twice !! You can check here 

reques

**Comment by sauravvsonu** [comment]
Sorry, I was getting conflict in others and, by mistake, created 3 PR. I have closed others 😜✌

**Comment by Ayushgup85** [comment]
is this issue still open?

**Comment by smaranjitghose** [comment]
> Sorry, I was getting conflict in others and, by mistake, created 3 PR. I have closed others 😜✌

Can you please pull the recent changes and squash them with this PR

**Comment by smaranjitghose** [comment]
footer_fk
This is what we can see from the PR [preview](https://deploy-preview-343--awesome-portfolio-website.netlify.app/projects.html)

**Pull request closed without merging**
