### PR TITLE
Project Page Search Bar UI Neumorphism

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue: #432 

Screenshot of the change:

- In Light Mode
image

- In Dark Mode
image

### CODE REVIEW

**Comment by sanjay270899** [comment]
Do add `DWOC` and `Level-x` label before merging. (Don't forget to add '-' in the level label)

Let me know if any changes needed. Thank You!

**Comment by smaranjitghose** [comment]
> Do add `DWOC` and `Level-x` label before merging. (Don't forget to add '-' in the level label)
> 
> Let me know if any changes needed. Thank You!

The light mode search bar is pitch perfect!
Can you please reduce the size of the search bar and place it on the topmost right corner between the illustration and the project cards. Although it's UI is important but it should not catch the UI so much so that the cards are secondary

**Comment by smaranjitghose** [comment]
> Issue: #432
> 
> Screenshot of the change:
> 
> * In Light Mode
>   image
> * In Dark Mode
>   image

Also can you please incorporate the recent changes to fix the merge conflict

**Comment by sanjay270899** [comment]
> > Do add `DWOC` and `Level-x` label before merging. (Don't forget to add '-' in the level label)
> > Let me know if any changes needed. Thank You!
> 
> The light mode search bar is pitch perfect!
> Can you please reduce the size of the search bar and place it on the topmost right corner between the illustration and the project cards. Although it's UI is important but it should not catch the UI so much so that the cards are secondary

I didn't get it. Can you show me in a screenshot?

And yes, I will resolve the merge conflict.

**Comment by sanjay270899** [comment]
@smaranjitghose I didn't get the exact location where I have to keep the search bar?

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Refer [this](https://webdevtrick.com/neumorphic-tabs-design/) for dark mode

**Comment by smaranjitghose** [comment]
> @smaranjitghose I didn't get the exact location where I have to keep the search bar?

project_page

**Comment by sanjay270899** [comment]
image

Improved Dark Mode:
Before
image
After
image

@smaranjitghose is it good?

**Comment by smaranjitghose** [comment]
> image
> 
> Improved Dark Mode:
> Before
> image
> After
> image
> 
> @smaranjitghose is it good?

In terms of UI it's superb!
Perhaps you can take up the issue for the footer after this.
Just a little bit of resizing required @sanjay270899

**Review by smaranjitghose — APPROVED** [review]

**Comment by sanjay270899** [comment]
@smaranjitghose Link in your last comment is not working.

And one request, please change the Label from `Level 4` to `Level-4`.

Thank you!

**Comment by smaranjitghose** [comment]
> @smaranjitghose Link in your last comment is not working.
> 
> And one request, please change the Label from `Level 4` to `Level-4`.
> 
> Thank you!

Update image as well as label! Thanks for bringing it to my notice

**Comment by sanjay270899** [comment]
@smaranjitghose @anushbhatia What is the level of this PR for SWOC, hard or meduim?

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia What is the level of this PR for SWOC, hard or meduim?

Hard

**Pull request merged**
