### PR TITLE
bugFix: fix image overflow in the research page

### LINKED ISSUE #962: Research Page Bug: Image Size Overflow
Reseearch_page_bug

### PR DESCRIPTION
**Pull request by battuAshita**
<h3>Fixes #962</h3>

## Work Done:

 - Fixed the problem of image overflow in he research page  
 - Updated research.css

## Relevant Screenshots and GIFs
<p>Before </p>

 
<p>After: </p>

### CODE REVIEW

**Comment by smaranjitghose** [comment]
imagess

The images should touch the edge of the card completely

**Comment by battuAshita** [comment]
Done :)

**Comment by smaranjitghose** [comment]
image
 
This has to be done for the top and bottom edges as well

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
Still this is same

**Comment by battuAshita** [comment]
Screenshot from 2021-07-18 09-37-32
This is how I am able to view it at my end.

**Comment by smaranjitghose** [comment]
In several mobile screens, the images in not aligned properly w.r.t the card and the card seems squeezed



mob_3

mob_2
mob_1

**Comment by battuAshita** [comment]
I have made the necessary changes. Please review and let me know :)

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
