### PR TITLE
Update Documentation

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
Fixes: #294 

# Proposed Changes
 - Updated `index.md`( I have added the Gifs & NWOC as Open Source Program).
 - Updated `contribution.md`.
  - Updated `team.md`. (Adding dynamic contributors no need to do it manually & deleting all contributors images and save some memory as well)

contributor
 
@anushbhatia May I change team.md or not ? Review my PR !! @smaranjitghose

### CODE REVIEW

**Comment by anushbhatia** [comment]
make changes in this pr with team members

**Comment by Vishal-raj-1** [comment]
> make changes in this pr with team members

Sure Sir !!

**Comment by Vishal-raj-1** [comment]
@smaranjitghose @anushbhatia Now `documentation` branch is updated as `README`

**Comment by smaranjitghose** [comment]
> Fixes: #294
> 
> # Proposed Changes
> * Updated `index.md`( I have added the Gifs & NWOC as Open Source Program).
> * Updated `contribution.md`.
> * Updated `team.md`. (Adding dynamic contributors no need to do it manually & deleting all contributors images and save some memory as well)
> 
> contributor
> 
> @anushbhatia May I change team.md or not ? Review my PR !! @smaranjitghose

Sure. Feel free to add your name brother!

**Pull request merged**
