### PR TITLE
Added neumorphism effects. Suggest enhancements, if any.

### PR DESCRIPTION
**Pull request by bhoomika07**
Before:
Screenshot 2021-01-01 at 11 21 57 PM
Screenshot 2021-01-01 at 11 22 32 PM

After:
Screenshot 2021-01-01 at 11 21 37 PM
Screenshot 2021-01-01 at 11 22 20 PM

### CODE REVIEW

**Comment by anushbhatia** [comment]
See the cards present [here](https://jwoc2k20.tech/) and for making of cards and UI u can use [this](https://neumorphism.io/).
Using neuromorphic design on one element doesn't make the complete page neuromorphic. Please use the same effect on all the pages and each and every element. You can for through each one of them one by one. If you need any suggestion please feel free to ask.
Do watch this for [demo](https://www.youtube.com/watch?v=bGW3mGn47dw)

**Comment by bhoomika07** [comment]
> See the cards present [here](https://jwoc2k20.tech/) and for making of cards and UI u can use [this](https://neumorphism.io/).
> Using neuromorphic design on one element doesn't make the complete page neuromorphic. Please use the same effect on all the pages and each and every element. You can for through each one of them one by one. If you need any suggestion please feel free to ask.
> Do watch this for [demo](https://www.youtube.com/watch?v=bGW3mGn47dw)

so should I do this for all the pages? The issue said education page, that's why did only one.

**Comment by smaranjitghose** [comment]
> > See the cards present [here](https://jwoc2k20.tech/) and for making of cards and UI u can use [this](https://neumorphism.io/).
> > Using neuromorphic design on one element doesn't make the complete page neuromorphic. Please use the same effect on all the pages and each and every element. You can for through each one of them one by one. If you need any suggestion please feel free to ask.
> > Do watch this for [demo](https://www.youtube.com/watch?v=bGW3mGn47dw)
> 
> so should I do this for all the pages? The issue said education page, that's why did only one.

First do it for education page. Once completed you can move on to other pages

**Comment by bhoomika07** [comment]
I have applied the neomorphic effects to the entire page, inclusive of all the elements.
Now, it looks something like this : 
Screenshot 2021-01-04 at 1 42 26 PM
Screenshot 2021-01-04 at 1 42 52 PM
Screenshot 2021-01-04 at 1 43 04 PM

**Comment by bhoomika07** [comment]
@smaranjitghose @anushbhatia please have a look, thanks!

**Comment by bhoomika07** [comment]
@smaranjitghose @anushbhatia can you review my changes, please?

**Comment by smaranjitghose** [comment]
> @smaranjitghose @anushbhatia can you review my changes, please?

I guess @anushbhatia gave you the changes over discord?

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://dribbble.com/stories/2020/03/05/neumorphism-ui-tips
Refer these colours see whenever we make any element in neuromorphic effect we either elevate a complete structure and inner shadow effect in 
refer [this](https://www.google.com/imgres?imgurl=https://i.pinimg.com/736x/b2/3d/b4/b23db4b09bda14592875df471446299e.jpg&imgrefurl=https://www.pinterest.com/pin/306596687135577965/&tbnid=GErs31_OLHOGKM&vet=1&docid=aby7TrSeRc8ioM&w=690&h=518&source=sh/x/im) for cards structure

**Review by anushbhatia — COMMENTED** [review]
border-radius: 50px;
background: #ecf0f3;
box-shadow: inset 9px 9px 18px #d7dadd,
            inset -9px -9px 18px #ffffff;
**Code For neumorphic design**

Use https://neumorphism.io/#ecf0f3

**Comment by smaranjitghose** [comment]
> #ecf0f

Use this website
https://neumorphism.io/

**Comment by bhoomika07** [comment]
Screenshot 2021-01-07 at 7 21 53 PM
Screenshot 2021-01-07 at 7 22 00 PM

Does this look fine now? Then I will make corresponding changes in dark mode as well.

**Comment by smaranjitghose** [comment]
Please raise a new PR as per the changes done for the project page done by me and @anushbhatia in the recent project page PR

**Pull request closed without merging**
