### PR TITLE
Fixed Theme-Toggler in the SideNav

### PR DESCRIPTION
**Pull request by chinmaym07**
issue no: #332 

Peek 2020-12-26 21-05

### CODE REVIEW

**Comment by chinmaym07** [comment]
Hey @smaranjitghose why did it failed at greetings .?
I have checked my corrections .It's working fine.
Can you please help .?

**Comment by smaranjitghose** [comment]
> Hey @smaranjitghose why did it failed at greetings .?
> I have checked my corrections .It's working fine.
> Can you please help .?

That's not your fault. It's an issue with the github action itself

**Comment by smaranjitghose** [comment]
@chinmaym07 Can you please reduce the transition speed of the toggle button in mobile view so that it is same as that of the web view

**Review by smaranjitghose — APPROVED** [review]

**Comment by chinmaym07** [comment]
> > Hey @smaranjitghose why did it failed at greetings .?
> > I have checked my corrections .It's working fine.
> > Can you please help .?
> 
> That's not your fault. It's an issue with the github action itself

Ohk.Thanks a lot.!
I'll make the required changes. 😀

**Comment by smaranjitghose** [comment]
NWOC, DWOC or  SWOC?

**Pull request merged**
