### PR TITLE
Converted into parallax depth card

### PR DESCRIPTION
**Pull request by AKC068**
ISSUE #743

> - Make the cards square.
> - Increase the size of the cards such that each row in the web view for a 15.6" screen has three cards.
> - Adjust the size of text (title of the card) such that 30 letters can be fit in a responsive manner. Multi-line titles should be possible.
> - On Hover, the title should not be displaced up instead the github and web icon (already present on the current cards on the website) should appear on the bottom right.

I have considered all the above mentioned points and successfully converted all those cards in "parallax depth card" and all are working properly with complete responsiveness.

@smaranjitghose and @anjali1102  please review my changes and let me know if this require any changes.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/40017559/123373572-3590ce00-d5a3-11eb-887d-f1b34add37d2.mp4

Weird bug when you hover for the first time.

**Comment by AKC068** [comment]
@anushbhatia sorry sir but I have checked.
There is no problem showing on my side related to that hover.

https://user-images.githubusercontent.com/59188454/123378302-324d1080-d5aa-11eb-9c8c-f1c169996586.mp4

**Comment by AKC068** [comment]
Also tried in microsoft edge in which you are browsing.
@anushbhatia

**Comment by smaranjitghose** [comment]
@AKC068 Could you please incorporate the recent changes to the repo and update your PR with a squash commit

**Comment by smaranjitghose** [comment]
## Feedback:

- The issue @anushbhatia mentioned is present irrespective of the browser being used.

It is observed less frequently but is not absent. A typical example would be when you scroll down and suddenly scroll up.

scroll_issue


- Reduce the shadow around the cards

- Remove the borders on the cards

- 2) and 3) of the issue description are expected

**Comment by AKC068** [comment]
> Could you please incorporate the recent changes to the repo and update your PR with a squash commit?
> and 3) of the issue description are expected

Ok, I'm doing it.
what do u mean by the last line?

**Comment by smaranjitghose** [comment]
> > Could you please incorporate the recent changes to the repo and update your PR with a squash commit?
> > and 3) of the issue description are expected
> 
> Ok, I'm doing it.
> what do u mean by the last line?

- No of cards per row should be 3. So resize them accordingly
- Experiment with multi-line titles or at least long titles having 30 characters

**Comment by smaranjitghose** [comment]
Code_redundancy

### Major Bug

**Comment by AKC068** [comment]
@smaranjitghose I got the bug.
Rest are ok sir.

**Comment by smaranjitghose** [comment]
## Weird Card Behaviour Persists


Mobile_View_Behaviour_2

-------------------------------------

Mobile_View_Behaviour




# Responsivenesss Issue Persists
Responsiveness_5

-------------------------------------------------------------
Responsiveness_3

-------------------------------------

Responsiveness_2

-------------------------------------

Responsiveness_1

-------------------------------------

Responsiveness_4

**Comment by AKC068** [comment]
@smaranjitghose sir this issue was only for making parallax depth card... I request u to merge my commits till now so that no other conflicts arise, as many times I faced the issue of conflicts, and let me create a new fresh issue for making this page fully responsive.

2nd the problem with the weird card behavior is that I'm not getting that weird behavior of card on my side, so it is difficult to find that bug.

And I'm working on the responsiveness of this page

**Comment by AKC068** [comment]
@smaranjitghose  Sir responsive issues are resolved.
I'm ready to make PR

image

image

image
image
image
image
image
image
image
image

**Review by smaranjitghose — APPROVED** [review]

**Comment by AKC068** [comment]
Sorry to disturb you @smaranjitghose sir, but my merged commits are not reflecting in the main [link](https://portfolio.smaranjitghose.com/projects.html).

**Pull request merged**
