### PR TITLE
Replaced Typewriter Effect with React Animation On Change

### PR DESCRIPTION
**Pull request by Anadee11**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Please refer the issue and the screenshot of the work in the issue description.
I am not sure if this was mentioned in any issue. @anushbhatia your thoughts?

**Review by anushbhatia — COMMENTED** [review]
Add a fade animation to that so that it looks better.

**Comment by smaranjitghose** [comment]
## Feedback:

1. [Reference] The "I am into" text should be in the same line as shown in the given reference.
2. Remove the Full stop at the end of the words Please


## Optional (but recommended)

1. Update the transition color: [Reference](https://www.koshex.com/)

**Comment by Anadee11** [comment]
@smaranjitghose sir updated the required changes i.e "I am into" text in the same line and no full stops.
Gave a try to changing transition colors but could not figure out. Thanks

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
