### PR TITLE
3d model with mouse effect component made

### LINKED ISSUE #865: 3D Terrain Effect in the Footer to replace the current illustration
- [Reference Video](https://www.youtube.com/watch?v=2AQLMZwQpDo&list=PL0lNJEnwfVVO4sNO2WDq_h73w-eHQStCB)
- Build it as a component

### PR DESCRIPTION
**Pull request by Serjeel-Ranjan-911**
A new component added. It's a 3d model imported with THREE.js which reacts to mouse. 

closes #865

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Can you attach the screenshot of the component so that we can see it.

**Comment by Serjeel-Ranjan-911** [comment]
@anushbhatia I already gave it under the issue #1048 . Plus I gave some extra details about it.

https://user-images.githubusercontent.com/74287984/134548713-e62a788c-969c-4aa7-a6d0-256ba79791cb.mp4

**Comment by Serjeel-Ranjan-911** [comment]
@smaranjitghose  any reasons why my pr was discarded?

**Comment by smaranjitghose** [comment]
Yes, on reviewing the [Deploy](https://awesome-portfolio-websites-git-fork-serje-969523-smaranjitghose.vercel.app/experience) of your PR, the changes were not reflected

**Comment by smaranjitghose** [comment]
Yes

**Pull request closed without merging**
