### PR TITLE
Volunteer Card UI Upadte in the Experience page

### PR DESCRIPTION
**Pull request by sakshi300699**
<h3>Issue Addressed - #571</h3> 

Based on the reference provided to me, I have updated the UI of the Volunteership Cards present in the Experience Page. All the points mentioned are covered.

I'm adding screenshots for reference.

John Doe _ Experience - Google Chrome 20-02-2021 23_59_38

<h3>Please review This PR.</h3>

### CODE REVIEW

**Comment by sakshi300699** [comment]
@smaranjitghose @anushbhatia Kindly review the PR.

**Comment by smaranjitghose** [comment]
@sakshi300699 Have a close look at the reference. The picture size plays a key role in making the card look relevant. Please follow the exact animation. 

@anushbhatia Could you please assist her with the color scheme

**Comment by sakshi300699** [comment]
@smaranjitghose by animation, do you mean the hover animation of card?

**Comment by smaranjitghose** [comment]
> @smaranjitghose by animation, do you mean the hover animation of card?

Yes

**Comment by sakshi300699** [comment]
https://user-images.githubusercontent.com/48864718/108633576-fa6a7b00-749a-11eb-8f92-53736afea916.mp4

@smaranjitghose I have added the exact animation and UI changes to the cards. Please see to the video attached. I'll make the PR if all the requirements are met.

**Comment by sakshi300699** [comment]
@smaranjitghose @anushbhatia should I make changes to the PR?

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image

**Comment by anushbhatia** [comment]
4c8bf5 refer this colour code for hover the keep the text white there also make the heading bold.

**Comment by sakshi300699** [comment]
@anushbhatia Is there some color specification for heading and box shadow?

**Comment by sakshi300699** [comment]
@smaranjitghose @anushbhatia Added the required edits. Please review and let me know if anything else is needed.

**Comment by anushbhatia** [comment]
keep the dark blue heading white

**Comment by sakshi300699** [comment]
> 
> 
> keep the dark blue heading white

@anushbhatia Done!

**Comment by sakshi300699** [comment]
Thank you @anushbhatia !

**Comment by smaranjitghose** [comment]
@sakshi300699 I just checked (my laptop had issues for some days so I could not reply earlier), the cards are too much elongated, please make the cards square and adjust the text size accordingly, do not change the headling color from black to blue. The headings (atleast one of them should fit in a line)

**Comment by sakshi300699** [comment]
> @sakshi300699 I just checked (my laptop had issues for some days so I could not reply earlier), the cards are too much elongated and hence weird, please make the cards square and adjust the text size accordingly, do not change the headling color from black to blue. The headings (atleast one of them should fit in a line)
> 
> Since rest of the changes are fine, I am not reverting this PR but try to rectify the above

@smaranjitghose I'll make the changes, just wanted to know that should I open another PR?

**Comment by smaranjitghose** [comment]
> > @sakshi300699 I just checked (my laptop had issues for some days so I could not reply earlier), the cards are too much elongated and hence weird, please make the cards square and adjust the text size accordingly, do not change the headling color from black to blue. The headings (atleast one of them should fit in a line)
> > Since rest of the changes are fine, I am not reverting this PR but try to rectify the above
> 
> @smaranjitghose I'll make the changes, just wanted to know that should I open another PR?

Yes as you have worked for the UI so this PR itself as per requirement, this PR is counted.
For the remaining changes, raise another PR please.

**Pull request merged**
