### PR TITLE
Navbar items alignment

### PR DESCRIPTION
**Pull request by Shruti025**
Fixes: #1270 

navbar items are now properly aligned.

### CODE REVIEW

**Comment by Shruti025** [comment]
@smaranjitghose @anushbhatia kindly review this PR

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
Also change the breakpoint for navbar in this it would great

**Comment by Shruti025** [comment]
I have updated it @anushbhatia let me know if this is alright or I need to update the mobile hook file.

**Review by anushbhatia — APPROVED** [review]
Great Work.
Really Appreciate for doing this

**Pull request merged**
