### PR TITLE
Modified the Work experience section.

### PR DESCRIPTION
**Pull request by Rishikakanojia**
@smaranjitghose @anushbhatia #112 #13 I've made changes in  work experience section as suggested.
screencapture-file-D-awesome-portfolio-websites-awesome-portfolio-websites-experience-html-2020-09-10-00_56_50

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@Rishikakanojia Looks good to me, kindly resolve the merge conflicts

**Review by shreyakapoor08 — CHANGES_REQUESTED** [review]
@Rishikakanojia Looks good to me, kindly resolve the merge conflicts

**Comment by Rishikakanojia** [comment]
@shreyakapoor08 I don't have the access to resolve this conflict. 
please help me.
screencapture-github-smaranjitghose-awesome-portfolio-websites-pull-130-2020-09-11-14_15_54

**Comment by smaranjitghose** [comment]
> @shreyakapoor08 I don't have the access to resolve this conflict.
> please help me.
> screencapture-github-smaranjitghose-awesome-portfolio-websites-pull-130-2020-09-11-14_15_54

You need to push commits for fixing it

**Comment by Rishikakanojia** [comment]
Thank you @smaranjitghose

**Comment by smaranjitghose** [comment]
I just checked you have changed files in .github directory which were not assigned to you. Please give a new pr and unstage those.
Additonally in my last feedback I had told that having a timeline for the experience as well as for the education page makes it repetitive so please come up something else. Have a look at the tasks in the slack channel

**Comment by Rishikakanojia** [comment]
@smaranjitghose Oh! Thanks. I'll try. thanks 👍🏽

**Pull request closed without merging**
