### PR TITLE
Njs home

### LINKED ISSUE #557: Shift Codebase to NextJS[Home Page]
Delete all the code in the nextjs branch, create a nextjs project and replicate the current home page

### PR DESCRIPTION
**Pull request by ashuvssut**
fixes #557 

Sorry for late PR. I was having trouble with particle.js and that animated-text.

**I created the main content of the Home page.** 

---------------
_--I have participated in DWoC SWoC and MWoC_

### CODE REVIEW

**Comment by ashuvssut** [comment]
I am working on education page and navbar and footer.

if you want to merge this home page, then you can do it. home page is all ready.
I can also make a follow up PR for footer and navbar

**Comment by anushbhatia** [comment]
NOw you can work on  the enhancement of this

**Comment by ashuvssut** [comment]
@anushbhatia plz review

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
When you navigate from education to research this is the error faced

**Comment by anushbhatia** [comment]
As communicated in other PR

**Pull request closed without merging**
