### PR TITLE
project page modified

### PR DESCRIPTION
**Pull request by mharshita**
@smaranjitghose  @anushbhatia  I have made the required changes to the project page. please review.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
projects_page
Small bug in the heading for the dark mode of mobile view. The "Project" word is overlapping with section below

**Comment by smaranjitghose** [comment]
I would like to make this project customizable for both male and female devs. So can inside ```assets/images/projects/``` can you have two illustrations one for a male dev, another for a female dev ( the current one is already cool). So that if someone wants to switch it can be easily done. You do not need to change it in the commit. Just attach a ss of the web and mobile view of the page with the other illustration

**Comment by smaranjitghose** [comment]
Also, can you please replace the current project data i.e. name,pic with something more generalized than than something that's derived of my own github. Have a look at freecodecamp's projects and put any 12 of those here (anything you like)

**Comment by mharshita** [comment]
@smaranjitghose  Okay!

**Comment by mharshita** [comment]
@smaranjitghose  I have made the required changes. Please review.

**Comment by mharshita** [comment]
image
image

**Comment by smaranjitghose** [comment]
Fantastic work @mharshita. One last bug to fix for this. You can do it in another PR.
projects_bug
In the mobile view, the description seems to pop up at the bottom of the card even without interaction.

**Comment by mharshita** [comment]
@smaranjitghose okay!

**Pull request merged**
