### PR TITLE
Modifications of social media icons

### PR DESCRIPTION
**Pull request by tirlochanarora16**
# Related Issues or bug
  -None

Fixes: #316

- [x] Footer bug
- [x] Added Instagram icon
- [x] Added icon for email
  
# Screenshots

 Original:image
Updated:image

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Dark Mode they work great @tirlochanarora16 but in the normal white mode it mixes with the background so have different colours for both the themes great work 🙌🙌.

**Comment by tirlochanarora16** [comment]
> Dark Mode they work great @tirlochanarora16 but in the normal white mode it mixes with the background so have different colors for both the themes great work 🙌🙌.

@anushbhatia, yeah I was thinking about it too, but can you suggest some colors that would look great in the normal mode?

**Comment by tirlochanarora16** [comment]
> > Dark Mode they work great @tirlochanarora16 but in the normal white mode it mixes with the background so have different colors for both the themes great work 🙌🙌.
> 
> @anushbhatia, yeah I was thinking about it too, but can you suggest some colors that would look great in the normal mode?

**Comment by tirlochanarora16** [comment]
> > Dark Mode they work great @tirlochanarora16 but in the normal white mode it mixes with the background so have different colors for both the themes great work 🙌🙌.
> 
> @anushbhatia, yeah I was thinking about it too, but can you suggest some colors that would look great in the normal mode?

**Comment by anushbhatia** [comment]
You can use grey and white

**Comment by tirlochanarora16** [comment]
> You can use grey and white combination for it

@anushbhatia Made those changes.

**Review by anushbhatia — APPROVED** [review]

**Comment by smaranjitghose** [comment]
> # Related Issues or bug
> -None
> 
> Fixes: #316
> 
> * [x]  Footer bug
> * [x]  Added Instagram icon
> * [x]  Added icon for email
> 
> # Screenshots
> Original:image
> Updated:image

Which open source programs are you a part of @tirlochanarora16 ?

**Comment by tirlochanarora16** [comment]
> Which open source programs are you a part of @tirlochanarora16 ?

@smaranjitghose, I am not a part of any open source program.

**Comment by smaranjitghose** [comment]
> > Which open source programs are you a part of @tirlochanarora16 ?
> 
> @smaranjitghose, I am not a part of any open source program.

Apply to SWoC and DWOC if you wish so that you can get an additional accreditation

**Comment by tirlochanarora16** [comment]
> Apply to SWoC and DWOC if you wish so that you can get an additional accreditation

@smaranjitghose, I am not familiar with SWOC and DWOC can you please tell what exactly are they?

**Comment by smaranjitghose** [comment]
Each of them are two month long open source programs:

DWOC: https://devscript.tech/woc/

SWOC: https://swoc.tech/

**Pull request merged**
