### PR TITLE
Project Page Card UI Update

### PR DESCRIPTION
**Pull request by Priyanshu-official**
Project Page Card UI Update #579

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@smaranjitghose pls Review PR sir

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
Resolve the responsiveness issue

**Comment by Priyanshu-official** [comment]
@smaranjitghose Sorry I will Do it

**Comment by Priyanshu-official** [comment]
@smaranjitghose Updated sir Review this PR and let me Know about UI enhancement

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
image

**Comment by Priyanshu-official** [comment]
@anushbhatia Ok Will do it Check all Responsive size
I didn't get it In my tab why it not show

**Comment by Priyanshu-official** [comment]
@anushbhatia @smaranjitghose   Pls Review
Hope all view Work

**Comment by anushbhatia** [comment]
image

**Comment by smaranjitghose** [comment]
Please see the issue description and the reference. I did not give it for no reason

**Pull request closed without merging**
