### PR TITLE
Experience Page Dark Mode UI Improvement

### LINKED ISSUE #963: Experience Page Dark Mode UI Improvement
## Current UI
image

# Sample Reference for Expected UI

Experience_Page

- Check out the social media buttons for dark mode on the home page as a reference for the same
- This should be done for all of the cards

### PR DESCRIPTION
**Pull request by bukolastella**
Fixes #963

# Work Done:

- Reflect dark mode changes on cards in of the Experience Page
- Change the color of the text on the card to from white to gray in dark mode
- Change the color of h2 tag to a lighter blue in dark mode

darkCapture

dark2Capture

### CODE REVIEW

**Comment by smaranjitghose** [comment]
color_scheme

Update the colors for this component as well, please. Rest looks good to me

**Review by smaranjitghose — APPROVED** [review]

**Comment by bukolastella** [comment]
Fixed it.

**Comment by bukolastella** [comment]
Fixed it.

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Nice work @bukolastella.

I have raised similar issues for the other pages as well. If you wish, you can take them up too

**Comment by bukolastella** [comment]
Alright, I  will see to it

**Pull request merged**
