### PR TITLE
NEW PR fixed the research button

### PR DESCRIPTION
**Pull request by Devmindtk**
added two more files and edit the research.js file

https://user-images.githubusercontent.com/91221069/156899231-eaad4b59-b0cc-4838-902b-8d531b3e3482.mp4

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Change the branch to reactjs

**Comment by Devmindtk** [comment]
> Change the branch to reactjs

done

**Comment by anushbhatia** [comment]
image
Change smaranjit:master to samranjit:reactjs because this pr is for react and do the same for both pr's

**Comment by Devmindtk** [comment]
> image Change smaranjit:master to samranjit:reactjs because this pr is for react and do the same for both pr's

already created a new pr in react js please check once #1265 pr

**Comment by Devmindtk** [comment]
> > image Change smaranjit:master to samranjit:reactjs because this pr is for react and do the same for both pr's
> 
> already created a new pr in react js please check once #1265 pr
Screenshot (510)

**Pull request closed without merging**
