### PR TITLE
Solved Images Overlapping Problem

### PR DESCRIPTION
**Pull request by Aayush-hub**
Fixes: #494  Improve Education Page Alignment

# Screenshot:
capi

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Arrows are barely visible so you can resolve this by either adding the navigators outside the certificate carousel or by adding colour on it so that it is visible on all background. I would prefer the first solution thou

**Comment by Aayush-hub** [comment]
@anushbhatia Sir , can I automate the task of sliding of certificates?

**Comment by smaranjitghose** [comment]
Please read properly what I had requested in your issue . By "remove the carosel" I mean remove the entire section itself

**Comment by Aayush-hub** [comment]
@smaranjitghose  Ohhky, so mean that certificate section is not needed!

**Pull request closed without merging**
