### PR TITLE
project page bug

### PR DESCRIPTION
**Pull request by mharshita**
@smaranjitghose  I have fixed the project page bug. Please review.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
porjects_bug
The bug is fixed for the rest of the cards, except the first one

**Comment by mharshita** [comment]
@smaranjitghose  sorry i didn't see that before. I have fixed it now. Please review again.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sorry i didn't see that before. I have fixed it now. Please review again.

Perfect the bug is fixed. There is one small edge case to be handled. At times our project name can be of 5-7 words. In that case, due to the large font size, it splits across multiple lines in the cards for the mobile view. I am merging this PR. Whenever you give a new PR for the other pages, could you please reduce the font size of the headings of the projects

**Comment by mharshita** [comment]
> > @smaranjitghose sorry i didn't see that before. I have fixed it now. Please review again.
> 
> Perfect the bug is fixed. There is one small edge case to be handled. At times our project name can be of 5-7 words. In that case, due to the large font size, it splits across multiple lines in the cards for the mobile view. I am merging this PR. Whenever you give a new PR for the other pages, could you please reduce the font size of the headings of the projects

@smaranjitghose Okay sir!

**Pull request merged**
