### PR TITLE
Animated Scroll Bar

### PR DESCRIPTION
**Pull request by achalesh27022003**
Added Animated Scroll Bar. Pls merge and level  label the PR under DWOC .

### CODE REVIEW

**Comment by achalesh27022003** [comment]
Pls review, merge and level label this PR under DWoC

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Don't add so many colours it looks too kiddish

**Comment by achalesh27022003** [comment]
> Don't add so many colours it looks too kiddish

Pls elaborate what is your concern. I have made it animated gradient custom scroll bar. I think it is looking good🙄.

**Comment by anushbhatia** [comment]
It looks good on sites where we want to show many colours at the same place but here were keep it minimal so the colour of black and blue with the decent colour and width will look great here.

**Comment by smaranjitghose** [comment]
> > Don't add so many colours it looks too kiddish
> 
> Pls elaborate what is your concern. I have made it animated gradient custom scroll bar. I think it is looking good🙄.

See it's not about if an individual element looks awesome or not. What matters is if it fits well with the rest of the system otherwise it would look really absurd.

The scrollbar you have made is really ideal for a dark theme based product page like those of ASUS ROG,etc. For a portfolio page of a person, perhaps not

**Pull request closed without merging**
