### PR TITLE
Fix the light mode not working after clicking light mode button toggle

### PR DESCRIPTION
**Pull request by stephenchinkenvun**
Fixed the light mode not working after clicking the light mode button toggle.

However, for the travel_temp.html page, the problem is not found anymore. I realized that sometimes when I select another page such as education, research, etc from my local directory, the light mode/dark mode will be swapped where dark mode with light background and light mode with a dark background. Not really sure what is the problem.

### CODE REVIEW

**Review by anushbhatia — COMMENTED** [review]
Text present on carousel is not visible in light mode properly if you solve it that would be great.

**Comment by stephenchinkenvun** [comment]
> Text present on carousel is not visible in light mode properly if you solve it that would be great.

**Comment by stephenchinkenvun** [comment]
> Text present on carousel is not visible in light mode properly if you solve it that would be great.

I will try to solve it

**Comment by anushbhatia** [comment]
@stephenchinkenvun any open source program you particularly belong to.

**Comment by stephenchinkenvun** [comment]
> any open source program you particularly belong to

not really

**Pull request merged**
