### PR TITLE
PR on the date color change in the dark theme #332

### PR DESCRIPTION
**Pull request by rajarshi-hub**
# Related Issues or bug
Date color change which was not visible in the dark mode

Fixes: #[332]

# Proposed Changes
Just including the class subtitle in experience.js file and  changing the subtitle class in the experinece.css file
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 
Screenshot (354)
 | **updated screenshot **|
Screenshot (353)

### CODE REVIEW

**Comment by smaranjitghose** [comment]
card_text

A bug that arises due to this fix

**Comment by rajarshi-hub** [comment]
> card_text
> 
> A bug that arises due to this fix



> card_text
> 
> A bug that arises due to this fix

Are you telling about the hovering bug in the volunteer card.
This error has not arisen due to this change in code.
It was happening previously and I mentioned it in #331 bug.
I have just changed date in the mentorship card

**Comment by rajarshi-hub** [comment]
Sir Can you tell me what is the problem in the checks and how to proceed further in this PR?

**Comment by anushbhatia** [comment]
text me over slack. Will explain in detail about the errors

**Pull request closed without merging**
