### PR TITLE
Solved #384

### PR DESCRIPTION
**Pull request by AdityaTeltia**
Given some margin top to solve the issue using ```mt-5``` .

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> Given some margin top to solve the issue using `mt-5` .

- Please refer the corresponding issue.
- Give a screenshot of before and after

**Comment by AdityaTeltia** [comment]
I have reffered the issue #384 
BEFORE:
not_responsive
AFTER:
after

**Review by anushbhatia — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Will be merged on 4th as per  SWoC guidelines

**Comment by AdityaTeltia** [comment]
Ok got it 👍

**Pull request merged**
