### PR TITLE
Added The carousel of Certificate #278

### PR DESCRIPTION
**Pull request by Tejas1510**
I have added the code for adding a carousel of the certificate which changes after an interval of 3 sec and fixes issue #278 
please review @anushbhatia , @smaranjitghose

### CODE REVIEW

**Comment by smaranjitghose** [comment]
> I have added the code for adding a carousel of the certificate which changes after an interval of 3 sec and fixes issue #278
> please review @anushbhatia , @smaranjitghose

Nice work. Could you please reduce the size to half.

**Comment by Tejas1510** [comment]
@smaranjitghose could you please specify which size like the interval or the number of certificate

**Comment by smaranjitghose** [comment]
> @smaranjitghose could you please specify which size like the interval or the number of certificate

the width and the height of the carousel

**Comment by Tejas1510** [comment]
@smaranjitghose Sure will make a PR soon

**Comment by Tejas1510** [comment]
@smaranjitghose I have made the height and width to half 
Please check it if you think it is ok

**Comment by smaranjitghose** [comment]
> @smaranjitghose I have made the height and width to half
> Please check it if you think it is ok

Nice work @Tejas1510 . Additionally we could have button (90 tilted V-shaped) on both sides so that if someone liked a particular achievement, they can come back and see it again

**Comment by Tejas1510** [comment]
@smaranjitghose will surely work on two-button to move left and right
Till then can you please update my score in the leaderboard

**Pull request merged**
