### PR TITLE
Add aos.int in Experience Section and proper align the cards in Home Page

### PR DESCRIPTION
**Pull request by bhavesh1129**
#442 
Hey @smaranjitghose,'

- I had added the feature of aos. int in the **Experience section** i.e on scrolling down the page you will see the particular section/card is jumping on the page or show animations that look cool and 
- Proper align the size of cards on the **Home page** as the UI hierarchy of cards isn't that good due to the different sizes so I had reduced the font size of card heading and to look it different from the other text written below I made it bold and give underline to it so that it looks nice on watching.

Hope you like my changes also if you want some changes that you can reply to me on this thread.
Thank you for assigning me this issue.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Add Fade animation and don't add experience section illustration two times. Also these animations make it feel like PPT try adding something really simple like fade effects or flip effect.

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://www.tutorialspoint.com/css/css_animation_fade_in.htm
Don't add the animation which is there in mentor and volunteering  section as this look pretty weird.
You can add basic and simple fade effects https://www.tutorialspoint.com/css/css_animation_fade_in.htm

**Comment by bhavesh1129** [comment]
> https://www.tutorialspoint.com/css/css_animation_fade_in.htm
> Don't add the animation which is there in mentor and volunteering section as this look pretty weird.
> You can add basic and simple fade effects https://www.tutorialspoint.com/css/css_animation_fade_in.htm

Sure I will!

**Comment by smaranjitghose** [comment]
Fix the merge conflicts and please give a  new PR

**Pull request closed without merging**
