### PR TITLE
Moocs cards are even and responsive

### PR DESCRIPTION
**Pull request by Rishikakanojia**
#83 @smaranjitghose Moocs cards' size has been fixed.
screencapture-file-D-awesome-portfolio-websites-awesome-portfolio-websites-education-html-2020-08-31-00_30_32

### CODE REVIEW

**Comment by anushbhatia** [comment]
Resolve merge conflict will merge it

**Comment by Rishikakanojia** [comment]
@anushbhatia sure, i'll try. :)

**Comment by Rishikakanojia** [comment]
@anushbhatia merge conflict has been resolved.

**Comment by Rishikakanojia** [comment]
@smaranjitghose can i now work on formal education section and if yes, could you please tell me whether i"ll make new branch to create PR or can continue to make changes in this branch only.

**Pull request merged**
