### PR TITLE
Footer Microanimation added

### LINKED ISSUE #796: Footer Microanimation
[Reference](https://codepen.io/nuski/details/ExPEBgw)

- The footer code should be loaded exclusively from app.js and style.css
- Modify the color according to the theme of the website

### PR DESCRIPTION
**Pull request by ishani02**
Fixes #796 

The send button is made according to the given reference and I have changed the color according to the website's color scheme.
I have made the button responsive as well.

Screen Shot 2021-06-30 at 9 07 19 AM

### CODE REVIEW

**Comment by smaranjitghose** [comment]
# Feedback:
- Please follow the current color theme of the website. I cannot merge another PR that disrupts the same
- The button is absurdly large and not aligned w.r.t the rest of the form
- The animation works irrespective of the input fields being empty or not. This is a basic bug
- Once the sent animation is complete, the page should show a pop up saying something like "Thanks for sending your message." and the form should be reset. Currently, the button just changes to sent and we cannot do anything with the form unless the page is refreshed which is a big UX caveat

**Comment by ishani02** [comment]
@smaranjitghose I have added the changes but whenever I add the condition to make the button work only when fields are filled, then on clicking the button, the page reloads.I have tried multiple ways to solve this like adding preventDefault method but I am unable to solve it.Can you please guide me?

**Comment by anushbhatia** [comment]
> @smaranjitghose I have added the changes but whenever I add the condition to make the button work only when fields are filled, then on clicking the button, the page reloads.I have tried multiple ways to solve this like adding preventDefault method but I am unable to solve it. Can you please guide me?

try adding a delay when it directs to a new page or if it redirects. The time taken by your animation should be the same as the delay. Also for now you can prevent it from going to another page somebody can link that later. If you still face issues feel free to contact us on respective communication channel

**Comment by ishani02** [comment]
@anushbhatia I tried adding delay as well but even that is not preventing the page from reloading on form resubmission. I think this can be solved during linking. I have added all the remaining above mentioned changes in the animation. Can you please review it and let me know if anything else should be done?

**Pull request closed without merging**
