### PR TITLE
added SVG animation to the project page

### PR DESCRIPTION
**Pull request by Abhijay007**
#574

preview:
project-page animation

### CODE REVIEW

**Comment by smaranjitghose** [comment]
One slight change:

- Keep the SVG to the left
- Heading and subheading to the right

**Review by smaranjitghose — APPROVED** [review]

**Comment by Abhijay007** [comment]
> One slight change:
> 
> * Keep the SVG to the left
> * Heading and subheading to the right

ok sir

**Comment by Abhijay007** [comment]
> One slight change:
> 
> * Keep the SVG to the left
> * Heading and subheading to the right

done sir!!

**Pull request merged**
