### PR TITLE
Added Linters for CSS, HTML, JS

### LINKED ISSUE #620: How about a JS/HTML/CSS Linter?
As this website is powered by JS, HTML and CSS, how about a linter for the same?

### PR DESCRIPTION
**Pull request by vybhav72954**
I have added a GitHub action for lining JS, CSS, and HTML.

Fixes #620

### CODE REVIEW

**Comment by vybhav72954** [comment]
PR has been marked as draft as this is a WIP.

**Comment by vybhav72954** [comment]
You can check the Action dashboard [here](https://github.com/smaranjitghose/awesome-portfolio-websites/actions/runs/613818043)

For now, the action ran on the whole codebase. I will change the action so that it runs on the PR.

**Comment by anushbhatia** [comment]
Which Program do you belong to

**Comment by vybhav72954** [comment]
@anushbhatia I doubt SWOC will accept this PR. So CrossWoc is the only suitable one

**Pull request merged**
