### PR TITLE
#316 : new icons added to body and footer

### PR DESCRIPTION
**Pull request by sauravvsonu**

### CODE REVIEW

**Comment by sauravvsonu** [comment]
solved issue #316 first part, adding the required logo.

**Comment by sauravvsonu** [comment]
( Greetings / greeting (pull_request) ) , this is falling while making a  pull request check. what is this and how to clear this

**Comment by smaranjitghose** [comment]
> ( Greetings / greeting (pull_request) ) , this is falling while making a pull request check. what is this and how to clear this

This is a simple github action to give an automated message when someone gives a PR and the maintainers are busy

**Comment by smaranjitghose** [comment]
Can you please fix the merge conflict by pulling the recent changes.

Also, could you please look up the recent icon for "Google Scholar"

**Pull request closed without merging**
