### PR TITLE
Added MOOCs

### PR DESCRIPTION
**Pull request by shubhkhanna**
@smaranjitghose @anushbhatia sir, please review it.
#14

### CODE REVIEW

**Comment by shubhkhanna** [comment]
@smaranjitghose, @anushbhatia sir, 
I've also added a header section in this PR, please consider it. #14

**Comment by arghac14** [comment]
@shubhkhanna looks good to me, you may try adding neumorphism to the moocs cards too like the way you did the formal education cards.

**Comment by shubhkhanna** [comment]
> @shubhkhanna looks good to me, you may try adding neumorphism to the moocs cards too like the way you did the formal education cards.

Sure.

**Comment by shubhkhanna** [comment]
> @shubhkhanna looks good to me, you may try adding neumorphism to the moocs cards too like the way you did the formal education cards.

@arghac14 Done.
Have a look on it.

**Comment by anushbhatia** [comment]
Next PR resolve the images thing in moocs section use something that doesn't stretch

**Pull request merged**
