### PR TITLE
New Pre-Loader (#752)

### PR DESCRIPTION
**Pull request by varunwho**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Fantastic work so far @varunwho !

@anushbhatia any suggestions for the color or the design?

**Review by anushbhatia — CHANGES_REQUESTED** [review]
All the elements in atoms are required to be changed.
Electrons(colours from slack, not a monocolour)
Paths(Blacks)

**Comment by varunwho** [comment]
Something like this?

https://user-images.githubusercontent.com/53107832/123046510-d18ece00-d419-11eb-9c5c-1ab957a6cf11.mp4

**Comment by anushbhatia** [comment]
This look fantastic to me @smaranjitghose any changes

**Comment by smaranjitghose** [comment]
Perfect. Just take care of the merge conflict. This  is ready for merge

**Comment by varunwho** [comment]
> Perfect. Just take care of the merge conflict. This  is ready for merge

Yea I'll create a new PR 🙌🏻

**Comment by smaranjitghose** [comment]
Continued and merged in follow up PR

**Pull request closed without merging**
