### PR TITLE
Created gallery page

### LINKED ISSUE #723: Create a page for gallery ( for art works of the portfolio owner )
A gallery section can be created in the portfolio. If you(@anushbhatia) approve and assign it to me, I can start the work.
This section can benefit ui/ux designers and other artists.

### PR DESCRIPTION
**Pull request by forkbikash**
Fixes #723

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Add this page in the navbar too.
Instead of 2 grid on the laptop try incorporating a 4/3 item grid. 
For mobile this design is lit✨

**Comment by forkbikash** [comment]
But smaranjitghose bhaiya told me to not put the link in the Navbar for now. Here( #723 ) is the conversation.
And also, I think simplicity of the design may get affected if I incorporate 4/3 item grid.

So,
Should I add the page in the navbar and incorporate 4/3 item grid ?

**Comment by anushbhatia** [comment]
okay, but in my suggestion having less scrolling on a laptop is the great user will look through all the mockups and designs then.

@smaranjitghose what say?
 
image
at least make the header's bold like all the other pages.

**Comment by forkbikash** [comment]
I made the header text bold ( @anushbhatia  )

**Comment by smaranjitghose** [comment]
responsiveness
Could you please fix the responsiveness issues on mobile screens?

**Comment by forkbikash** [comment]
Is it responsive now?. If not please tell me what is the exact issue, else please merge it.
And also I will try to implement AOS in the next PR after learning it ( If you allow ). @smaranjitghose

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
> Is it responsive now?. If not please tell me what is the exact issue, else please merge it.
> And also I will try to implement AOS in the next PR after learning it ( If you allow ). @smaranjitghose

Sure. you can raise an issue for it and raise the corresponding PR related to AOS for this page

**Pull request merged**
