### PR TITLE
experience-card

### PR DESCRIPTION
**Pull request by salonilakhotia**
I have made some changes in work-experience-card. Kindly review the changes and let me know If I need to add or remove anything.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
everything is too much vertical so it won't match with UI.

**Comment by smaranjitghose** [comment]
@salonilakhotia  Any updates?

**Comment by salonilakhotia** [comment]
@smaranjitghose Sir I will try to make new design in weekend.If not then I will let u know after that.

**Comment by salonilakhotia** [comment]
@smaranjitghose @anushbhatia Sir I have made the changes. Kindly see it once.

**Comment by smaranjitghose** [comment]
I really don't feel horizontal cards are a good design for displaying experience
Instead, you can reduce the size of the existing cards, change the headings like the role is too large and the place of work is not. The duration could be aligned towards the right. Soft UI can be implemented. Do not put links to research papers😅. We want to keep the page as much generalized as possible. Try improving the bullet points

@anushbhatia can you give more elaborate pointers

**Comment by salonilakhotia** [comment]
@smaranjitghose Sir..Actually I have shown first to @anushbhatia Sir before generating the PR.

**Comment by anushbhatia** [comment]
But he recommended some changes please follow them. I can guide you if you have a problem.

**Comment by anushbhatia** [comment]
Any Updates @salonilakhotia

**Comment by Rishikakanojia** [comment]
@smaranjitghose  can i work on this?

**Comment by anushbhatia** [comment]
sure

**Pull request closed without merging**
