### PR TITLE
Fix responsiveness in Home Page

### LINKED ISSUE #817: Fix responsiveness in Home Page
error

The text **Hi, I am John Doe** is hidden when the screen size is 1355px * 542px and less.

Also, the social media icons can be made a bit smaller and fit into a single row.

### PR DESCRIPTION
**Pull request by Yunika-Bajracharya**
# Resolves #817 

# Work done:

- Fixed the responsiveness of the text **Hi, I am John Doe** on the home page for all screen sizes.
- Optimized the size of social icons so that they fit in a single row for larger screen sizes.

# Relevant Screenshots:
first
second

### CODE REVIEW

**Comment by smaranjitghose** [comment]
## Feedback:


- The size of the social media icons is not to be altered.

social_media_icons

- The dribble icon's micronization is messed up in web view

- Responsiveness issue in the following screen size

Responsiveness_Issue

**Comment by Yunika-Bajracharya** [comment]
Resolves #817 

@smaranjitghose Thank you for the feedback. Here are the corrections I have made:

- Restored the size of the social media icons.
- Fixed the responsiveness issue in the following size:

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
@Yunika-Bajracharya Nice work!




## Further Feedback:

- The page is responsive for almost all screen sizes. Kudos to you.
- However, I believe if we can alter the size of the icons/text in the Ipad, IPad pro size screens, and make more social media icons appear in a single line, we can improve the UI further.
- The above suggestion is not required to be met for the fulfillment of the requirements of the issue corresponding to this PR. If you wish to contribute further and make those changes, you can raise another issue and work on a follow-up PR for the same  



ipad_Pro


--------------------------------------------------

ipad

**Comment by Yunika-Bajracharya** [comment]
Thanks a lot! 😄
I'll look for further improvements in UI as per your suggestions.

**Pull request merged**
