### PR TITLE
Finally bug is resolved.

### PR DESCRIPTION
**Pull request by jatinjain001**
https://user-images.githubusercontent.com/46483236/107559968-c40f3f00-6c02-11eb-9494-b0185b836cf1.mp4

Now you can check the video I attached , and its perfect now.

### CODE REVIEW

**Review by anushbhatia — COMMENTED** [review]
image
Check at this resolution

**Comment by jatinjain001** [comment]
Check now changes updated

**Review by anushbhatia — APPROVED** [review]

**Comment by anushbhatia** [comment]
Which programs are you part of?

**Comment by smaranjitghose** [comment]
project_card_1
project_card_2

@anushbhatia the width of the layer below the text is different in the first card w.r.t to the others. But I believe we can improve this another PR.

**Comment by jatinjain001** [comment]
Bro please add the tag of DWOC cause they are not counting this PR in Contribution , But I contributed in it So please consider it in DWOC contribution and give my points under DWOC , Add the tag of DWOC Please

**Comment by smaranjitghose** [comment]
> Bro please add the tag of DWOC cause they are not counting this PR in Contribution , But I contributed in it So please consider it in DWOC contribution and give my points under DWOC , Add the tag of DWOC Please

Done

**Pull request merged**
