### PR TITLE
bugFix: remove scroll-bar during preload

### LINKED ISSUE #882: Scroll Bar Bug during Pre-Loader
The Scroll bar appears during the pre-loader animation which is unexpected behavior
Scroll_Bar_bug

### PR DESCRIPTION
**Pull request by battuAshita**
<h3>Fixes #882</h3>

## Work Done:

 - Fixed the Scroll-bar bug in the preloader page
 - Updated index.html, preloader.css and app.js

## Relevant Screenshots and GIFs
<p>This is how it looked previously: </p>

 
<p>After fixing the bug, it looks like this: </p>

### CODE REVIEW

**Comment by smaranjitghose** [comment]
- The issue persists when we switch pages
scroll_bar

**Comment by smaranjitghose** [comment]
Oh. Just checked. Do make the changes for all the pages 😅. Rest looks fine to me

**Comment by battuAshita** [comment]
Thank you :)
Will do the necessary changes and get back.

**Comment by battuAshita** [comment]
Please review my changes :)

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Congratulations @battuAshita  for getting your first PR merged 🎉🎉🎉

**Pull request merged**
