### PR TITLE
Improved responsiveness

### PR DESCRIPTION
**Pull request by samyukta20**
Changed fixed dimensions to responsive.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
home_font
Font size is too large 😅

**Comment by samyukta20** [comment]
Please check the changed one. And please tell me if further changes needed.

**Comment by shreyakapoor08** [comment]
> Please check the changed one. And please tell me if further changes needed.

Looks fine now

**Comment by samyukta20** [comment]
> > Please check the changed one. And please tell me if further changes needed.
> 
> Looks fine now

Okay, thanks

**Pull request merged**
