### PR TITLE
Added feather fa icon

### LINKED ISSUE #852: Font awesome icon not visible in footer
image
The left quote icon is a blank square on the **education** page.

### PR DESCRIPTION
**Pull request by supzi-del**
Fixes #852

### CODE REVIEW

**Comment by smaranjitghose** [comment]
By feather icon I meant [this](https://feathericons.com/) 😅

**Comment by supzi-del** [comment]
> By feather icon I meant [this](https://feathericons.com/) 😅

Is there a quote icon in feather icons?

**Comment by smaranjitghose** [comment]
You can use [this](https://iconify.design/icon-sets/fe/quote-left.html). Click on the SVG Tab, get the code, Open it AdobeXD/Figma and obtain the file

**Comment by supzi-del** [comment]
Hope changes in this commit is what you're looking for! ☝️

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
