### PR TITLE
added constraints to textarea

### PR DESCRIPTION
**Pull request by dipanshparmar**
Fixes: #372 

# Proposed Changes
 - Added minimum height and maximum height to avoid overflows and shrink issues

  
# Screenshots
**Before**
min height
image

**After**
min height
image

***
**Before**
max height(infinite**
image

**After*
max height (limited)
image

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@smaranjitghose please have a look.

**Comment by smaranjitghose** [comment]
> @smaranjitghose please have a look.

This is for NWOC right?

**Comment by dipanshparmar** [comment]
> > @smaranjitghose please have a look.
> 
> This is for NWOC right?

Nope! I didn't participate there.

**Comment by smaranjitghose** [comment]
NWOC or  DWOC or  SWOC?

**Comment by dipanshparmar** [comment]
SWOC

**Pull request merged**
