### PR TITLE
added SVG animation to the sidebar of mobile view

### PR DESCRIPTION
**Pull request by Abhijay007**
added SVG animation to the sidebar of mobile view

#521 
preview:
bike animation

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Have a look at the deploy [preview](https://deploy-preview-600--awesome-portfolio-website.netlify.app/) please and try to rectify the bug

**Comment by Abhijay007** [comment]
But sir it looks fine in my mobile screen ? Can you please explain which
bug you are referring to?

I will try to improve that

**Comment by smaranjitghose** [comment]
reduce_nav)space

Also, try to reduce this unnecessary space

**Comment by Abhijay007** [comment]
Ok sir

**Comment by Abhijay007** [comment]
@smaranjitghose sir I am done with the responsiveness and also removed that unnecessary space between contents and header:

responsive-sidebar

**Comment by Abhijay007** [comment]
> 

but sir can you please specify that where this bug showed because I am not able to find something like this in my codebase.
I try very viewport point but unable to find it

**Comment by Abhijay007** [comment]
> @smaranjitghose sir I am done with the responsiveness and also removed that unnecessary space between contents and header:
> 
> responsive-sidebar

sir if you want me to reduce more space between contents and header for any specific mobile view I will do that.

**Comment by smaranjitghose** [comment]
> 
> 
> > 
> 
> but sir can you please specify that where this bug showed because I am not able to find something like this in my codebase.
> I try very viewport point but unable to find it

In my chrome it works fine, the issue arises in my firefox

**Comment by Abhijay007** [comment]
> > > 
> > 
> > 
> > but sir can you please specify that where this bug showed because I am not able to find something like this in my codebase.
> > I try very viewport point but unable to find it
> 
> In my chrome it works fine, the issue arises in my firefox

@smaranjitghose sir can you suggest me something to resolve this in firefox, I don't use firefox 😅 so don't know about that much

**Comment by smaranjitghose** [comment]
We can have a separate issue for that, since this is working for most screens and browsers, I'll merge it for now.

BTW, @Abhijay007 @anushbhatia   could you get firefox and confirm if the issue is just from my end or it's consistent for your browsers too

**Comment by Abhijay007** [comment]
> We can have a separate issue for that, since this is working for most screens and browsers, I'll merge it for now.
> 
> BTW, @Abhijay007 @anushbhatia could you get firefox and confirm if the issue is just from my end or it's consistent for your browsers too

ok sir

**Comment by Abhijay007** [comment]
> BTW, @Abhijay007 @anushbhatia could you get firefox and confirm if the issue is just from my end or it's consistent for your browsers too

firefox

Yes @smaranjitghose sir, confirmed !!

**Comment by anushbhatia** [comment]
image
Resolve this problem of alignment and illustration size in the phase of tablets in desktop and mobile it works fine.

**Comment by Abhijay007** [comment]
> image
> Resolve this problem of alignment and illustration size in the phase of tablets in desktop and mobile it works fine.
> Raise a new PR

ok sir

**Pull request merged**
