### PR TITLE
experienceDarkMode

### PR DESCRIPTION
**Pull request by Amrutha1101**
Resolved issue #803.
Color fixed for all the cards in experience page in dark mode.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
In mentorship cards, it feels the cards are stuck on the page add a bit more blur so that they can pop out more.

In open-source, the card avoids the x-axis aspect of the box-shadow and keep that to 0px.

**Comment by smaranjitghose** [comment]
@Amrutha1101 There are some recent changes that have been incorporated to improve the responsiveness as well as the UI. Make sure to pull those commits into your working branch before making the changes

**Comment by smaranjitghose** [comment]
@Amrutha1101 any updates?

**Comment by Amrutha1101** [comment]
I'm left with fixing box-shadow of open source cards

**Comment by Amrutha1101** [comment]
Can you close this PR as I'm creating one more PR as the files in my local system got deleted?

**Comment by Amrutha1101** [comment]
> In mentorship cards, it feels the cards are stuck on the page add a bit more blur so that they can pop out more.
> 
> In open-source, the card avoids the x-axis aspect of the box-shadow and keep that to 0px.

The open source card what is mentioned is it for both light and dark mode or only dark mode?

**Comment by anushbhatia** [comment]
light mode

**Pull request closed without merging**
