### PR TITLE
Issue #473. Redesigned the research page. Details in the PR

### PR DESCRIPTION
**Pull request by ishubham21**
1. Removed all the code for 'Abstract' and 'Cite' popup.
2. Facilitated the expansion of abstract and BibTex divs.
3. Changed the bg color of the page
4. Improvised the design of cards.
5. Removed useless chunks of code.
Screenshot (105)
Screenshot (104)

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
Fantastic work @ishubham21 
As far as features are concerned, the research page is complete imho
@anushbhatia can further tell you about UI improvements like button design, color, etc

**Comment by anushbhatia** [comment]
hover effect on buttons can be improved by adding black colour with no effect on it.

**Comment by smaranjitghose** [comment]
> hover effect on buttons can be improved by adding black colour with no effect on it.

@ishubham21

**Comment by ishubham21** [comment]
> hover effect on buttons can be improved by adding black colour with no effect on it.

Sorry, I didn't see your message earlier today. 

Can you please explain this a bit more? I'm not able to exactly gather your instruction.

**Comment by smaranjitghose** [comment]
> > hover effect on buttons can be improved by adding black colour with no effect on it.
> 
> Sorry, I didn't see your message earlier today.
> 
> Can you please explain this a bit more? I'm not able to exactly gather your instruction.

@anushbhatia. Could you please elaborate a little more on this for @ishubham21

**Pull request merged**
