### PR TITLE
Popup box feature successfully imported

### PR DESCRIPTION
**Pull request by ROHAN842**
Fixes Issue #725 
I successfully added an alert which will pops up and will tell the user that message was delivered successfully with a green tick and displaying message as "Thank you for the response. John will get in touch soon!" along with I also added a feature without back end with which user would be sent to a fresh new page on clicking Send button where the message is displayed as "Thank you We received your submission , Return ".

https://user-images.githubusercontent.com/61961107/122599779-80cf4c00-d08c-11eb-93b2-8f40ad497c08.mp4

### CODE REVIEW

**Comment by ROHAN842** [comment]
Hey @smaranjitghose I request you to merge my new Updated PR also I have imported changes in it.

**Comment by aliya-rahmani** [comment]
@ROHAN842  There are some improper spacing in your code(improper indentation), please fix them.

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/40017559/122629495-18f42200-d0db-11eb-9464-395416ce547b.mp4

**Comment by anushbhatia** [comment]
after completing all the fields then it should show the congrats message there.

**Comment by ROHAN842** [comment]
Hey @anushbhatia I was facing some issue in that alert Popup feature as the message was not popping up after completing all checks that's why I removed that feature only and now when user will fill all the details then only he will be redirected to a fresh new page where the message is displayed as "Thank You! We received your submission" Return back to home page.
So now I request you to kindly merge my PR

**Pull request merged**
