### PR TITLE
UI Improvement: converted 2 columns into 3

### PR DESCRIPTION
**Pull request by dipanshparmar**
# Proposed Changes
 - Implemented flexbox
 - Increased the no. of projects in a row
  
# Screenshots
**Before**
image

**After**
image

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Reduce the size of the card by a little bit and cause when we reduce the size of the screen by 10 per cent in the laptop then we can see gird of 3 and when we view it at 100 we can see only 2 grids.
In mobile view, the cards are showing the tech stack which should only be view once a user on mobile clicks it and then the popup should show the tech stack.

**Comment by dipanshparmar** [comment]
> In mobile view, the cards are showing the tech stack which should only be view once a user on mobile clicks it and then the popup should show the tech stack.

**fixed the 'tech stack is showing by default in mobile view**

> Reduce the size of the card by a little bit and cause when we reduce the size of the screen by 10 per cent in the laptop then we can see gird of 3 and when we view it at 100 we can see only 2 grids.

**What do you mean by 100 here?**

**Comment by anushbhatia** [comment]
https://user-images.githubusercontent.com/40017559/103915156-db08d000-5130-11eb-9df1-645552159e67.mp4

**Comment by dipanshparmar** [comment]
>  John.Doe._.Projects.and.4.more.pages.-.Personal.-.Microsoft.Edge.2021-01-07.21-37-31_Trim.mp4

got it.

**Comment by dipanshparmar** [comment]
@anushbhatia Is it okay now? I can not confirm it on my localhost because it was already showing me 3 cards before.

**Review by smaranjitghose — APPROVED** [review]
Nice work @dipanshparmar

**Comment by dipanshparmar** [comment]
Thanks @smaranjitghose :smile:

**Pull request merged**
